
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  User: 'User',
  FeatureSelections: 'FeatureSelections',
  JournalEntry: 'JournalEntry',
  WorkoutLog: 'WorkoutLog',
  CalendarItem: 'CalendarItem',
  SleepLog: 'SleepLog',
  AnalyzerFinding: 'AnalyzerFinding',
  AiWorkoutPlan: 'AiWorkoutPlan'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const FeatureSelectionsScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  calendar: 'calendar',
  journal: 'journal',
  aiWorkout: 'aiWorkout',
  sleep: 'sleep',
  createdAt: 'createdAt'
} as const

export type FeatureSelectionsScalarFieldEnum = (typeof FeatureSelectionsScalarFieldEnum)[keyof typeof FeatureSelectionsScalarFieldEnum]


export const JournalEntryScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  content: 'content',
  sentiment: 'sentiment',
  positivityTag: 'positivityTag',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type JournalEntryScalarFieldEnum = (typeof JournalEntryScalarFieldEnum)[keyof typeof JournalEntryScalarFieldEnum]


export const WorkoutLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  scheduledDate: 'scheduledDate',
  completed: 'completed',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkoutLogScalarFieldEnum = (typeof WorkoutLogScalarFieldEnum)[keyof typeof WorkoutLogScalarFieldEnum]


export const CalendarItemScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  dueDate: 'dueDate',
  completed: 'completed',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CalendarItemScalarFieldEnum = (typeof CalendarItemScalarFieldEnum)[keyof typeof CalendarItemScalarFieldEnum]


export const SleepLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  startTime: 'startTime',
  endTime: 'endTime',
  quality: 'quality',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SleepLogScalarFieldEnum = (typeof SleepLogScalarFieldEnum)[keyof typeof SleepLogScalarFieldEnum]


export const AnalyzerFindingScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  title: 'title',
  message: 'message',
  severity: 'severity',
  createdAt: 'createdAt'
} as const

export type AnalyzerFindingScalarFieldEnum = (typeof AnalyzerFindingScalarFieldEnum)[keyof typeof AnalyzerFindingScalarFieldEnum]


export const AiWorkoutPlanScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  requestPayload: 'requestPayload',
  responsePayload: 'responsePayload',
  artifactPath: 'artifactPath',
  createdAt: 'createdAt'
} as const

export type AiWorkoutPlanScalarFieldEnum = (typeof AiWorkoutPlanScalarFieldEnum)[keyof typeof AiWorkoutPlanScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]

