
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AnalyzerFinding` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AnalyzerFinding
 * 
 */
export type AnalyzerFindingModel = runtime.Types.Result.DefaultSelection<Prisma.$AnalyzerFindingPayload>

export type AggregateAnalyzerFinding = {
  _count: AnalyzerFindingCountAggregateOutputType | null
  _avg: AnalyzerFindingAvgAggregateOutputType | null
  _sum: AnalyzerFindingSumAggregateOutputType | null
  _min: AnalyzerFindingMinAggregateOutputType | null
  _max: AnalyzerFindingMaxAggregateOutputType | null
}

export type AnalyzerFindingAvgAggregateOutputType = {
  severity: number | null
}

export type AnalyzerFindingSumAggregateOutputType = {
  severity: number | null
}

export type AnalyzerFindingMinAggregateOutputType = {
  id: string | null
  userId: string | null
  type: $Enums.FindingType | null
  title: string | null
  message: string | null
  severity: number | null
  createdAt: Date | null
}

export type AnalyzerFindingMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  type: $Enums.FindingType | null
  title: string | null
  message: string | null
  severity: number | null
  createdAt: Date | null
}

export type AnalyzerFindingCountAggregateOutputType = {
  id: number
  userId: number
  type: number
  title: number
  message: number
  severity: number
  createdAt: number
  _all: number
}


export type AnalyzerFindingAvgAggregateInputType = {
  severity?: true
}

export type AnalyzerFindingSumAggregateInputType = {
  severity?: true
}

export type AnalyzerFindingMinAggregateInputType = {
  id?: true
  userId?: true
  type?: true
  title?: true
  message?: true
  severity?: true
  createdAt?: true
}

export type AnalyzerFindingMaxAggregateInputType = {
  id?: true
  userId?: true
  type?: true
  title?: true
  message?: true
  severity?: true
  createdAt?: true
}

export type AnalyzerFindingCountAggregateInputType = {
  id?: true
  userId?: true
  type?: true
  title?: true
  message?: true
  severity?: true
  createdAt?: true
  _all?: true
}

export type AnalyzerFindingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AnalyzerFinding to aggregate.
   */
  where?: Prisma.AnalyzerFindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnalyzerFindings to fetch.
   */
  orderBy?: Prisma.AnalyzerFindingOrderByWithRelationInput | Prisma.AnalyzerFindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AnalyzerFindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnalyzerFindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnalyzerFindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AnalyzerFindings
  **/
  _count?: true | AnalyzerFindingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AnalyzerFindingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AnalyzerFindingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AnalyzerFindingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AnalyzerFindingMaxAggregateInputType
}

export type GetAnalyzerFindingAggregateType<T extends AnalyzerFindingAggregateArgs> = {
      [P in keyof T & keyof AggregateAnalyzerFinding]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAnalyzerFinding[P]>
    : Prisma.GetScalarType<T[P], AggregateAnalyzerFinding[P]>
}




export type AnalyzerFindingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AnalyzerFindingWhereInput
  orderBy?: Prisma.AnalyzerFindingOrderByWithAggregationInput | Prisma.AnalyzerFindingOrderByWithAggregationInput[]
  by: Prisma.AnalyzerFindingScalarFieldEnum[] | Prisma.AnalyzerFindingScalarFieldEnum
  having?: Prisma.AnalyzerFindingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AnalyzerFindingCountAggregateInputType | true
  _avg?: AnalyzerFindingAvgAggregateInputType
  _sum?: AnalyzerFindingSumAggregateInputType
  _min?: AnalyzerFindingMinAggregateInputType
  _max?: AnalyzerFindingMaxAggregateInputType
}

export type AnalyzerFindingGroupByOutputType = {
  id: string
  userId: string
  type: $Enums.FindingType
  title: string
  message: string
  severity: number
  createdAt: Date
  _count: AnalyzerFindingCountAggregateOutputType | null
  _avg: AnalyzerFindingAvgAggregateOutputType | null
  _sum: AnalyzerFindingSumAggregateOutputType | null
  _min: AnalyzerFindingMinAggregateOutputType | null
  _max: AnalyzerFindingMaxAggregateOutputType | null
}

type GetAnalyzerFindingGroupByPayload<T extends AnalyzerFindingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AnalyzerFindingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AnalyzerFindingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AnalyzerFindingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AnalyzerFindingGroupByOutputType[P]>
      }
    >
  >



export type AnalyzerFindingWhereInput = {
  AND?: Prisma.AnalyzerFindingWhereInput | Prisma.AnalyzerFindingWhereInput[]
  OR?: Prisma.AnalyzerFindingWhereInput[]
  NOT?: Prisma.AnalyzerFindingWhereInput | Prisma.AnalyzerFindingWhereInput[]
  id?: Prisma.StringFilter<"AnalyzerFinding"> | string
  userId?: Prisma.StringFilter<"AnalyzerFinding"> | string
  type?: Prisma.EnumFindingTypeFilter<"AnalyzerFinding"> | $Enums.FindingType
  title?: Prisma.StringFilter<"AnalyzerFinding"> | string
  message?: Prisma.StringFilter<"AnalyzerFinding"> | string
  severity?: Prisma.IntFilter<"AnalyzerFinding"> | number
  createdAt?: Prisma.DateTimeFilter<"AnalyzerFinding"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type AnalyzerFindingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  message?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type AnalyzerFindingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AnalyzerFindingWhereInput | Prisma.AnalyzerFindingWhereInput[]
  OR?: Prisma.AnalyzerFindingWhereInput[]
  NOT?: Prisma.AnalyzerFindingWhereInput | Prisma.AnalyzerFindingWhereInput[]
  userId?: Prisma.StringFilter<"AnalyzerFinding"> | string
  type?: Prisma.EnumFindingTypeFilter<"AnalyzerFinding"> | $Enums.FindingType
  title?: Prisma.StringFilter<"AnalyzerFinding"> | string
  message?: Prisma.StringFilter<"AnalyzerFinding"> | string
  severity?: Prisma.IntFilter<"AnalyzerFinding"> | number
  createdAt?: Prisma.DateTimeFilter<"AnalyzerFinding"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type AnalyzerFindingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  message?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AnalyzerFindingCountOrderByAggregateInput
  _avg?: Prisma.AnalyzerFindingAvgOrderByAggregateInput
  _max?: Prisma.AnalyzerFindingMaxOrderByAggregateInput
  _min?: Prisma.AnalyzerFindingMinOrderByAggregateInput
  _sum?: Prisma.AnalyzerFindingSumOrderByAggregateInput
}

export type AnalyzerFindingScalarWhereWithAggregatesInput = {
  AND?: Prisma.AnalyzerFindingScalarWhereWithAggregatesInput | Prisma.AnalyzerFindingScalarWhereWithAggregatesInput[]
  OR?: Prisma.AnalyzerFindingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AnalyzerFindingScalarWhereWithAggregatesInput | Prisma.AnalyzerFindingScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AnalyzerFinding"> | string
  userId?: Prisma.StringWithAggregatesFilter<"AnalyzerFinding"> | string
  type?: Prisma.EnumFindingTypeWithAggregatesFilter<"AnalyzerFinding"> | $Enums.FindingType
  title?: Prisma.StringWithAggregatesFilter<"AnalyzerFinding"> | string
  message?: Prisma.StringWithAggregatesFilter<"AnalyzerFinding"> | string
  severity?: Prisma.IntWithAggregatesFilter<"AnalyzerFinding"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AnalyzerFinding"> | Date | string
}

export type AnalyzerFindingCreateInput = {
  id?: string
  type: $Enums.FindingType
  title: string
  message: string
  severity: number
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAnalyzerFindingsInput
}

export type AnalyzerFindingUncheckedCreateInput = {
  id?: string
  userId: string
  type: $Enums.FindingType
  title: string
  message: string
  severity: number
  createdAt?: Date | string
}

export type AnalyzerFindingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFindingTypeFieldUpdateOperationsInput | $Enums.FindingType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAnalyzerFindingsNestedInput
}

export type AnalyzerFindingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFindingTypeFieldUpdateOperationsInput | $Enums.FindingType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalyzerFindingCreateManyInput = {
  id?: string
  userId: string
  type: $Enums.FindingType
  title: string
  message: string
  severity: number
  createdAt?: Date | string
}

export type AnalyzerFindingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFindingTypeFieldUpdateOperationsInput | $Enums.FindingType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalyzerFindingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFindingTypeFieldUpdateOperationsInput | $Enums.FindingType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalyzerFindingListRelationFilter = {
  every?: Prisma.AnalyzerFindingWhereInput
  some?: Prisma.AnalyzerFindingWhereInput
  none?: Prisma.AnalyzerFindingWhereInput
}

export type AnalyzerFindingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AnalyzerFindingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  message?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AnalyzerFindingAvgOrderByAggregateInput = {
  severity?: Prisma.SortOrder
}

export type AnalyzerFindingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  message?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AnalyzerFindingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  title?: Prisma.SortOrder
  message?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AnalyzerFindingSumOrderByAggregateInput = {
  severity?: Prisma.SortOrder
}

export type AnalyzerFindingCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AnalyzerFindingCreateWithoutUserInput, Prisma.AnalyzerFindingUncheckedCreateWithoutUserInput> | Prisma.AnalyzerFindingCreateWithoutUserInput[] | Prisma.AnalyzerFindingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AnalyzerFindingCreateOrConnectWithoutUserInput | Prisma.AnalyzerFindingCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AnalyzerFindingCreateManyUserInputEnvelope
  connect?: Prisma.AnalyzerFindingWhereUniqueInput | Prisma.AnalyzerFindingWhereUniqueInput[]
}

export type AnalyzerFindingUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AnalyzerFindingCreateWithoutUserInput, Prisma.AnalyzerFindingUncheckedCreateWithoutUserInput> | Prisma.AnalyzerFindingCreateWithoutUserInput[] | Prisma.AnalyzerFindingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AnalyzerFindingCreateOrConnectWithoutUserInput | Prisma.AnalyzerFindingCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AnalyzerFindingCreateManyUserInputEnvelope
  connect?: Prisma.AnalyzerFindingWhereUniqueInput | Prisma.AnalyzerFindingWhereUniqueInput[]
}

export type AnalyzerFindingUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AnalyzerFindingCreateWithoutUserInput, Prisma.AnalyzerFindingUncheckedCreateWithoutUserInput> | Prisma.AnalyzerFindingCreateWithoutUserInput[] | Prisma.AnalyzerFindingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AnalyzerFindingCreateOrConnectWithoutUserInput | Prisma.AnalyzerFindingCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AnalyzerFindingUpsertWithWhereUniqueWithoutUserInput | Prisma.AnalyzerFindingUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AnalyzerFindingCreateManyUserInputEnvelope
  set?: Prisma.AnalyzerFindingWhereUniqueInput | Prisma.AnalyzerFindingWhereUniqueInput[]
  disconnect?: Prisma.AnalyzerFindingWhereUniqueInput | Prisma.AnalyzerFindingWhereUniqueInput[]
  delete?: Prisma.AnalyzerFindingWhereUniqueInput | Prisma.AnalyzerFindingWhereUniqueInput[]
  connect?: Prisma.AnalyzerFindingWhereUniqueInput | Prisma.AnalyzerFindingWhereUniqueInput[]
  update?: Prisma.AnalyzerFindingUpdateWithWhereUniqueWithoutUserInput | Prisma.AnalyzerFindingUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AnalyzerFindingUpdateManyWithWhereWithoutUserInput | Prisma.AnalyzerFindingUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AnalyzerFindingScalarWhereInput | Prisma.AnalyzerFindingScalarWhereInput[]
}

export type AnalyzerFindingUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AnalyzerFindingCreateWithoutUserInput, Prisma.AnalyzerFindingUncheckedCreateWithoutUserInput> | Prisma.AnalyzerFindingCreateWithoutUserInput[] | Prisma.AnalyzerFindingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AnalyzerFindingCreateOrConnectWithoutUserInput | Prisma.AnalyzerFindingCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AnalyzerFindingUpsertWithWhereUniqueWithoutUserInput | Prisma.AnalyzerFindingUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AnalyzerFindingCreateManyUserInputEnvelope
  set?: Prisma.AnalyzerFindingWhereUniqueInput | Prisma.AnalyzerFindingWhereUniqueInput[]
  disconnect?: Prisma.AnalyzerFindingWhereUniqueInput | Prisma.AnalyzerFindingWhereUniqueInput[]
  delete?: Prisma.AnalyzerFindingWhereUniqueInput | Prisma.AnalyzerFindingWhereUniqueInput[]
  connect?: Prisma.AnalyzerFindingWhereUniqueInput | Prisma.AnalyzerFindingWhereUniqueInput[]
  update?: Prisma.AnalyzerFindingUpdateWithWhereUniqueWithoutUserInput | Prisma.AnalyzerFindingUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AnalyzerFindingUpdateManyWithWhereWithoutUserInput | Prisma.AnalyzerFindingUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AnalyzerFindingScalarWhereInput | Prisma.AnalyzerFindingScalarWhereInput[]
}

export type EnumFindingTypeFieldUpdateOperationsInput = {
  set?: $Enums.FindingType
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type AnalyzerFindingCreateWithoutUserInput = {
  id?: string
  type: $Enums.FindingType
  title: string
  message: string
  severity: number
  createdAt?: Date | string
}

export type AnalyzerFindingUncheckedCreateWithoutUserInput = {
  id?: string
  type: $Enums.FindingType
  title: string
  message: string
  severity: number
  createdAt?: Date | string
}

export type AnalyzerFindingCreateOrConnectWithoutUserInput = {
  where: Prisma.AnalyzerFindingWhereUniqueInput
  create: Prisma.XOR<Prisma.AnalyzerFindingCreateWithoutUserInput, Prisma.AnalyzerFindingUncheckedCreateWithoutUserInput>
}

export type AnalyzerFindingCreateManyUserInputEnvelope = {
  data: Prisma.AnalyzerFindingCreateManyUserInput | Prisma.AnalyzerFindingCreateManyUserInput[]
}

export type AnalyzerFindingUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.AnalyzerFindingWhereUniqueInput
  update: Prisma.XOR<Prisma.AnalyzerFindingUpdateWithoutUserInput, Prisma.AnalyzerFindingUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AnalyzerFindingCreateWithoutUserInput, Prisma.AnalyzerFindingUncheckedCreateWithoutUserInput>
}

export type AnalyzerFindingUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.AnalyzerFindingWhereUniqueInput
  data: Prisma.XOR<Prisma.AnalyzerFindingUpdateWithoutUserInput, Prisma.AnalyzerFindingUncheckedUpdateWithoutUserInput>
}

export type AnalyzerFindingUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.AnalyzerFindingScalarWhereInput
  data: Prisma.XOR<Prisma.AnalyzerFindingUpdateManyMutationInput, Prisma.AnalyzerFindingUncheckedUpdateManyWithoutUserInput>
}

export type AnalyzerFindingScalarWhereInput = {
  AND?: Prisma.AnalyzerFindingScalarWhereInput | Prisma.AnalyzerFindingScalarWhereInput[]
  OR?: Prisma.AnalyzerFindingScalarWhereInput[]
  NOT?: Prisma.AnalyzerFindingScalarWhereInput | Prisma.AnalyzerFindingScalarWhereInput[]
  id?: Prisma.StringFilter<"AnalyzerFinding"> | string
  userId?: Prisma.StringFilter<"AnalyzerFinding"> | string
  type?: Prisma.EnumFindingTypeFilter<"AnalyzerFinding"> | $Enums.FindingType
  title?: Prisma.StringFilter<"AnalyzerFinding"> | string
  message?: Prisma.StringFilter<"AnalyzerFinding"> | string
  severity?: Prisma.IntFilter<"AnalyzerFinding"> | number
  createdAt?: Prisma.DateTimeFilter<"AnalyzerFinding"> | Date | string
}

export type AnalyzerFindingCreateManyUserInput = {
  id?: string
  type: $Enums.FindingType
  title: string
  message: string
  severity: number
  createdAt?: Date | string
}

export type AnalyzerFindingUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFindingTypeFieldUpdateOperationsInput | $Enums.FindingType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalyzerFindingUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFindingTypeFieldUpdateOperationsInput | $Enums.FindingType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AnalyzerFindingUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFindingTypeFieldUpdateOperationsInput | $Enums.FindingType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AnalyzerFindingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  type?: boolean
  title?: boolean
  message?: boolean
  severity?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["analyzerFinding"]>

export type AnalyzerFindingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  type?: boolean
  title?: boolean
  message?: boolean
  severity?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["analyzerFinding"]>

export type AnalyzerFindingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  type?: boolean
  title?: boolean
  message?: boolean
  severity?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["analyzerFinding"]>

export type AnalyzerFindingSelectScalar = {
  id?: boolean
  userId?: boolean
  type?: boolean
  title?: boolean
  message?: boolean
  severity?: boolean
  createdAt?: boolean
}

export type AnalyzerFindingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "type" | "title" | "message" | "severity" | "createdAt", ExtArgs["result"]["analyzerFinding"]>
export type AnalyzerFindingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AnalyzerFindingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AnalyzerFindingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $AnalyzerFindingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AnalyzerFinding"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    type: $Enums.FindingType
    title: string
    message: string
    severity: number
    createdAt: Date
  }, ExtArgs["result"]["analyzerFinding"]>
  composites: {}
}

export type AnalyzerFindingGetPayload<S extends boolean | null | undefined | AnalyzerFindingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AnalyzerFindingPayload, S>

export type AnalyzerFindingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AnalyzerFindingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AnalyzerFindingCountAggregateInputType | true
  }

export interface AnalyzerFindingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AnalyzerFinding'], meta: { name: 'AnalyzerFinding' } }
  /**
   * Find zero or one AnalyzerFinding that matches the filter.
   * @param {AnalyzerFindingFindUniqueArgs} args - Arguments to find a AnalyzerFinding
   * @example
   * // Get one AnalyzerFinding
   * const analyzerFinding = await prisma.analyzerFinding.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AnalyzerFindingFindUniqueArgs>(args: Prisma.SelectSubset<T, AnalyzerFindingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AnalyzerFindingClient<runtime.Types.Result.GetResult<Prisma.$AnalyzerFindingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AnalyzerFinding that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AnalyzerFindingFindUniqueOrThrowArgs} args - Arguments to find a AnalyzerFinding
   * @example
   * // Get one AnalyzerFinding
   * const analyzerFinding = await prisma.analyzerFinding.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AnalyzerFindingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AnalyzerFindingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AnalyzerFindingClient<runtime.Types.Result.GetResult<Prisma.$AnalyzerFindingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AnalyzerFinding that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalyzerFindingFindFirstArgs} args - Arguments to find a AnalyzerFinding
   * @example
   * // Get one AnalyzerFinding
   * const analyzerFinding = await prisma.analyzerFinding.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AnalyzerFindingFindFirstArgs>(args?: Prisma.SelectSubset<T, AnalyzerFindingFindFirstArgs<ExtArgs>>): Prisma.Prisma__AnalyzerFindingClient<runtime.Types.Result.GetResult<Prisma.$AnalyzerFindingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AnalyzerFinding that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalyzerFindingFindFirstOrThrowArgs} args - Arguments to find a AnalyzerFinding
   * @example
   * // Get one AnalyzerFinding
   * const analyzerFinding = await prisma.analyzerFinding.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AnalyzerFindingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AnalyzerFindingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AnalyzerFindingClient<runtime.Types.Result.GetResult<Prisma.$AnalyzerFindingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AnalyzerFindings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalyzerFindingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AnalyzerFindings
   * const analyzerFindings = await prisma.analyzerFinding.findMany()
   * 
   * // Get first 10 AnalyzerFindings
   * const analyzerFindings = await prisma.analyzerFinding.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const analyzerFindingWithIdOnly = await prisma.analyzerFinding.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AnalyzerFindingFindManyArgs>(args?: Prisma.SelectSubset<T, AnalyzerFindingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnalyzerFindingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AnalyzerFinding.
   * @param {AnalyzerFindingCreateArgs} args - Arguments to create a AnalyzerFinding.
   * @example
   * // Create one AnalyzerFinding
   * const AnalyzerFinding = await prisma.analyzerFinding.create({
   *   data: {
   *     // ... data to create a AnalyzerFinding
   *   }
   * })
   * 
   */
  create<T extends AnalyzerFindingCreateArgs>(args: Prisma.SelectSubset<T, AnalyzerFindingCreateArgs<ExtArgs>>): Prisma.Prisma__AnalyzerFindingClient<runtime.Types.Result.GetResult<Prisma.$AnalyzerFindingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AnalyzerFindings.
   * @param {AnalyzerFindingCreateManyArgs} args - Arguments to create many AnalyzerFindings.
   * @example
   * // Create many AnalyzerFindings
   * const analyzerFinding = await prisma.analyzerFinding.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AnalyzerFindingCreateManyArgs>(args?: Prisma.SelectSubset<T, AnalyzerFindingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AnalyzerFindings and returns the data saved in the database.
   * @param {AnalyzerFindingCreateManyAndReturnArgs} args - Arguments to create many AnalyzerFindings.
   * @example
   * // Create many AnalyzerFindings
   * const analyzerFinding = await prisma.analyzerFinding.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AnalyzerFindings and only return the `id`
   * const analyzerFindingWithIdOnly = await prisma.analyzerFinding.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AnalyzerFindingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AnalyzerFindingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnalyzerFindingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AnalyzerFinding.
   * @param {AnalyzerFindingDeleteArgs} args - Arguments to delete one AnalyzerFinding.
   * @example
   * // Delete one AnalyzerFinding
   * const AnalyzerFinding = await prisma.analyzerFinding.delete({
   *   where: {
   *     // ... filter to delete one AnalyzerFinding
   *   }
   * })
   * 
   */
  delete<T extends AnalyzerFindingDeleteArgs>(args: Prisma.SelectSubset<T, AnalyzerFindingDeleteArgs<ExtArgs>>): Prisma.Prisma__AnalyzerFindingClient<runtime.Types.Result.GetResult<Prisma.$AnalyzerFindingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AnalyzerFinding.
   * @param {AnalyzerFindingUpdateArgs} args - Arguments to update one AnalyzerFinding.
   * @example
   * // Update one AnalyzerFinding
   * const analyzerFinding = await prisma.analyzerFinding.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AnalyzerFindingUpdateArgs>(args: Prisma.SelectSubset<T, AnalyzerFindingUpdateArgs<ExtArgs>>): Prisma.Prisma__AnalyzerFindingClient<runtime.Types.Result.GetResult<Prisma.$AnalyzerFindingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AnalyzerFindings.
   * @param {AnalyzerFindingDeleteManyArgs} args - Arguments to filter AnalyzerFindings to delete.
   * @example
   * // Delete a few AnalyzerFindings
   * const { count } = await prisma.analyzerFinding.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AnalyzerFindingDeleteManyArgs>(args?: Prisma.SelectSubset<T, AnalyzerFindingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AnalyzerFindings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalyzerFindingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AnalyzerFindings
   * const analyzerFinding = await prisma.analyzerFinding.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AnalyzerFindingUpdateManyArgs>(args: Prisma.SelectSubset<T, AnalyzerFindingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AnalyzerFindings and returns the data updated in the database.
   * @param {AnalyzerFindingUpdateManyAndReturnArgs} args - Arguments to update many AnalyzerFindings.
   * @example
   * // Update many AnalyzerFindings
   * const analyzerFinding = await prisma.analyzerFinding.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AnalyzerFindings and only return the `id`
   * const analyzerFindingWithIdOnly = await prisma.analyzerFinding.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AnalyzerFindingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AnalyzerFindingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnalyzerFindingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AnalyzerFinding.
   * @param {AnalyzerFindingUpsertArgs} args - Arguments to update or create a AnalyzerFinding.
   * @example
   * // Update or create a AnalyzerFinding
   * const analyzerFinding = await prisma.analyzerFinding.upsert({
   *   create: {
   *     // ... data to create a AnalyzerFinding
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AnalyzerFinding we want to update
   *   }
   * })
   */
  upsert<T extends AnalyzerFindingUpsertArgs>(args: Prisma.SelectSubset<T, AnalyzerFindingUpsertArgs<ExtArgs>>): Prisma.Prisma__AnalyzerFindingClient<runtime.Types.Result.GetResult<Prisma.$AnalyzerFindingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AnalyzerFindings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalyzerFindingCountArgs} args - Arguments to filter AnalyzerFindings to count.
   * @example
   * // Count the number of AnalyzerFindings
   * const count = await prisma.analyzerFinding.count({
   *   where: {
   *     // ... the filter for the AnalyzerFindings we want to count
   *   }
   * })
  **/
  count<T extends AnalyzerFindingCountArgs>(
    args?: Prisma.Subset<T, AnalyzerFindingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AnalyzerFindingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AnalyzerFinding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalyzerFindingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AnalyzerFindingAggregateArgs>(args: Prisma.Subset<T, AnalyzerFindingAggregateArgs>): Prisma.PrismaPromise<GetAnalyzerFindingAggregateType<T>>

  /**
   * Group by AnalyzerFinding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AnalyzerFindingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AnalyzerFindingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AnalyzerFindingGroupByArgs['orderBy'] }
      : { orderBy?: AnalyzerFindingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AnalyzerFindingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAnalyzerFindingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AnalyzerFinding model
 */
readonly fields: AnalyzerFindingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AnalyzerFinding.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AnalyzerFindingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AnalyzerFinding model
 */
export interface AnalyzerFindingFieldRefs {
  readonly id: Prisma.FieldRef<"AnalyzerFinding", 'String'>
  readonly userId: Prisma.FieldRef<"AnalyzerFinding", 'String'>
  readonly type: Prisma.FieldRef<"AnalyzerFinding", 'FindingType'>
  readonly title: Prisma.FieldRef<"AnalyzerFinding", 'String'>
  readonly message: Prisma.FieldRef<"AnalyzerFinding", 'String'>
  readonly severity: Prisma.FieldRef<"AnalyzerFinding", 'Int'>
  readonly createdAt: Prisma.FieldRef<"AnalyzerFinding", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AnalyzerFinding findUnique
 */
export type AnalyzerFindingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalyzerFinding
   */
  select?: Prisma.AnalyzerFindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalyzerFinding
   */
  omit?: Prisma.AnalyzerFindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalyzerFindingInclude<ExtArgs> | null
  /**
   * Filter, which AnalyzerFinding to fetch.
   */
  where: Prisma.AnalyzerFindingWhereUniqueInput
}

/**
 * AnalyzerFinding findUniqueOrThrow
 */
export type AnalyzerFindingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalyzerFinding
   */
  select?: Prisma.AnalyzerFindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalyzerFinding
   */
  omit?: Prisma.AnalyzerFindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalyzerFindingInclude<ExtArgs> | null
  /**
   * Filter, which AnalyzerFinding to fetch.
   */
  where: Prisma.AnalyzerFindingWhereUniqueInput
}

/**
 * AnalyzerFinding findFirst
 */
export type AnalyzerFindingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalyzerFinding
   */
  select?: Prisma.AnalyzerFindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalyzerFinding
   */
  omit?: Prisma.AnalyzerFindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalyzerFindingInclude<ExtArgs> | null
  /**
   * Filter, which AnalyzerFinding to fetch.
   */
  where?: Prisma.AnalyzerFindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnalyzerFindings to fetch.
   */
  orderBy?: Prisma.AnalyzerFindingOrderByWithRelationInput | Prisma.AnalyzerFindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AnalyzerFindings.
   */
  cursor?: Prisma.AnalyzerFindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnalyzerFindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnalyzerFindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AnalyzerFindings.
   */
  distinct?: Prisma.AnalyzerFindingScalarFieldEnum | Prisma.AnalyzerFindingScalarFieldEnum[]
}

/**
 * AnalyzerFinding findFirstOrThrow
 */
export type AnalyzerFindingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalyzerFinding
   */
  select?: Prisma.AnalyzerFindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalyzerFinding
   */
  omit?: Prisma.AnalyzerFindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalyzerFindingInclude<ExtArgs> | null
  /**
   * Filter, which AnalyzerFinding to fetch.
   */
  where?: Prisma.AnalyzerFindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnalyzerFindings to fetch.
   */
  orderBy?: Prisma.AnalyzerFindingOrderByWithRelationInput | Prisma.AnalyzerFindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AnalyzerFindings.
   */
  cursor?: Prisma.AnalyzerFindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnalyzerFindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnalyzerFindings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AnalyzerFindings.
   */
  distinct?: Prisma.AnalyzerFindingScalarFieldEnum | Prisma.AnalyzerFindingScalarFieldEnum[]
}

/**
 * AnalyzerFinding findMany
 */
export type AnalyzerFindingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalyzerFinding
   */
  select?: Prisma.AnalyzerFindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalyzerFinding
   */
  omit?: Prisma.AnalyzerFindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalyzerFindingInclude<ExtArgs> | null
  /**
   * Filter, which AnalyzerFindings to fetch.
   */
  where?: Prisma.AnalyzerFindingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AnalyzerFindings to fetch.
   */
  orderBy?: Prisma.AnalyzerFindingOrderByWithRelationInput | Prisma.AnalyzerFindingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AnalyzerFindings.
   */
  cursor?: Prisma.AnalyzerFindingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AnalyzerFindings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AnalyzerFindings.
   */
  skip?: number
  distinct?: Prisma.AnalyzerFindingScalarFieldEnum | Prisma.AnalyzerFindingScalarFieldEnum[]
}

/**
 * AnalyzerFinding create
 */
export type AnalyzerFindingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalyzerFinding
   */
  select?: Prisma.AnalyzerFindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalyzerFinding
   */
  omit?: Prisma.AnalyzerFindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalyzerFindingInclude<ExtArgs> | null
  /**
   * The data needed to create a AnalyzerFinding.
   */
  data: Prisma.XOR<Prisma.AnalyzerFindingCreateInput, Prisma.AnalyzerFindingUncheckedCreateInput>
}

/**
 * AnalyzerFinding createMany
 */
export type AnalyzerFindingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AnalyzerFindings.
   */
  data: Prisma.AnalyzerFindingCreateManyInput | Prisma.AnalyzerFindingCreateManyInput[]
}

/**
 * AnalyzerFinding createManyAndReturn
 */
export type AnalyzerFindingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalyzerFinding
   */
  select?: Prisma.AnalyzerFindingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AnalyzerFinding
   */
  omit?: Prisma.AnalyzerFindingOmit<ExtArgs> | null
  /**
   * The data used to create many AnalyzerFindings.
   */
  data: Prisma.AnalyzerFindingCreateManyInput | Prisma.AnalyzerFindingCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalyzerFindingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AnalyzerFinding update
 */
export type AnalyzerFindingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalyzerFinding
   */
  select?: Prisma.AnalyzerFindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalyzerFinding
   */
  omit?: Prisma.AnalyzerFindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalyzerFindingInclude<ExtArgs> | null
  /**
   * The data needed to update a AnalyzerFinding.
   */
  data: Prisma.XOR<Prisma.AnalyzerFindingUpdateInput, Prisma.AnalyzerFindingUncheckedUpdateInput>
  /**
   * Choose, which AnalyzerFinding to update.
   */
  where: Prisma.AnalyzerFindingWhereUniqueInput
}

/**
 * AnalyzerFinding updateMany
 */
export type AnalyzerFindingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AnalyzerFindings.
   */
  data: Prisma.XOR<Prisma.AnalyzerFindingUpdateManyMutationInput, Prisma.AnalyzerFindingUncheckedUpdateManyInput>
  /**
   * Filter which AnalyzerFindings to update
   */
  where?: Prisma.AnalyzerFindingWhereInput
  /**
   * Limit how many AnalyzerFindings to update.
   */
  limit?: number
}

/**
 * AnalyzerFinding updateManyAndReturn
 */
export type AnalyzerFindingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalyzerFinding
   */
  select?: Prisma.AnalyzerFindingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AnalyzerFinding
   */
  omit?: Prisma.AnalyzerFindingOmit<ExtArgs> | null
  /**
   * The data used to update AnalyzerFindings.
   */
  data: Prisma.XOR<Prisma.AnalyzerFindingUpdateManyMutationInput, Prisma.AnalyzerFindingUncheckedUpdateManyInput>
  /**
   * Filter which AnalyzerFindings to update
   */
  where?: Prisma.AnalyzerFindingWhereInput
  /**
   * Limit how many AnalyzerFindings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalyzerFindingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AnalyzerFinding upsert
 */
export type AnalyzerFindingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalyzerFinding
   */
  select?: Prisma.AnalyzerFindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalyzerFinding
   */
  omit?: Prisma.AnalyzerFindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalyzerFindingInclude<ExtArgs> | null
  /**
   * The filter to search for the AnalyzerFinding to update in case it exists.
   */
  where: Prisma.AnalyzerFindingWhereUniqueInput
  /**
   * In case the AnalyzerFinding found by the `where` argument doesn't exist, create a new AnalyzerFinding with this data.
   */
  create: Prisma.XOR<Prisma.AnalyzerFindingCreateInput, Prisma.AnalyzerFindingUncheckedCreateInput>
  /**
   * In case the AnalyzerFinding was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AnalyzerFindingUpdateInput, Prisma.AnalyzerFindingUncheckedUpdateInput>
}

/**
 * AnalyzerFinding delete
 */
export type AnalyzerFindingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalyzerFinding
   */
  select?: Prisma.AnalyzerFindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalyzerFinding
   */
  omit?: Prisma.AnalyzerFindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalyzerFindingInclude<ExtArgs> | null
  /**
   * Filter which AnalyzerFinding to delete.
   */
  where: Prisma.AnalyzerFindingWhereUniqueInput
}

/**
 * AnalyzerFinding deleteMany
 */
export type AnalyzerFindingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AnalyzerFindings to delete
   */
  where?: Prisma.AnalyzerFindingWhereInput
  /**
   * Limit how many AnalyzerFindings to delete.
   */
  limit?: number
}

/**
 * AnalyzerFinding without action
 */
export type AnalyzerFindingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalyzerFinding
   */
  select?: Prisma.AnalyzerFindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalyzerFinding
   */
  omit?: Prisma.AnalyzerFindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalyzerFindingInclude<ExtArgs> | null
}
