
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FeatureSelections` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FeatureSelections
 * 
 */
export type FeatureSelectionsModel = runtime.Types.Result.DefaultSelection<Prisma.$FeatureSelectionsPayload>

export type AggregateFeatureSelections = {
  _count: FeatureSelectionsCountAggregateOutputType | null
  _min: FeatureSelectionsMinAggregateOutputType | null
  _max: FeatureSelectionsMaxAggregateOutputType | null
}

export type FeatureSelectionsMinAggregateOutputType = {
  id: string | null
  userId: string | null
  calendar: boolean | null
  journal: boolean | null
  aiWorkout: boolean | null
  sleep: boolean | null
  createdAt: Date | null
}

export type FeatureSelectionsMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  calendar: boolean | null
  journal: boolean | null
  aiWorkout: boolean | null
  sleep: boolean | null
  createdAt: Date | null
}

export type FeatureSelectionsCountAggregateOutputType = {
  id: number
  userId: number
  calendar: number
  journal: number
  aiWorkout: number
  sleep: number
  createdAt: number
  _all: number
}


export type FeatureSelectionsMinAggregateInputType = {
  id?: true
  userId?: true
  calendar?: true
  journal?: true
  aiWorkout?: true
  sleep?: true
  createdAt?: true
}

export type FeatureSelectionsMaxAggregateInputType = {
  id?: true
  userId?: true
  calendar?: true
  journal?: true
  aiWorkout?: true
  sleep?: true
  createdAt?: true
}

export type FeatureSelectionsCountAggregateInputType = {
  id?: true
  userId?: true
  calendar?: true
  journal?: true
  aiWorkout?: true
  sleep?: true
  createdAt?: true
  _all?: true
}

export type FeatureSelectionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FeatureSelections to aggregate.
   */
  where?: Prisma.FeatureSelectionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeatureSelections to fetch.
   */
  orderBy?: Prisma.FeatureSelectionsOrderByWithRelationInput | Prisma.FeatureSelectionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FeatureSelectionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeatureSelections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeatureSelections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FeatureSelections
  **/
  _count?: true | FeatureSelectionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FeatureSelectionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FeatureSelectionsMaxAggregateInputType
}

export type GetFeatureSelectionsAggregateType<T extends FeatureSelectionsAggregateArgs> = {
      [P in keyof T & keyof AggregateFeatureSelections]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFeatureSelections[P]>
    : Prisma.GetScalarType<T[P], AggregateFeatureSelections[P]>
}




export type FeatureSelectionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FeatureSelectionsWhereInput
  orderBy?: Prisma.FeatureSelectionsOrderByWithAggregationInput | Prisma.FeatureSelectionsOrderByWithAggregationInput[]
  by: Prisma.FeatureSelectionsScalarFieldEnum[] | Prisma.FeatureSelectionsScalarFieldEnum
  having?: Prisma.FeatureSelectionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FeatureSelectionsCountAggregateInputType | true
  _min?: FeatureSelectionsMinAggregateInputType
  _max?: FeatureSelectionsMaxAggregateInputType
}

export type FeatureSelectionsGroupByOutputType = {
  id: string
  userId: string
  calendar: boolean
  journal: boolean
  aiWorkout: boolean
  sleep: boolean
  createdAt: Date
  _count: FeatureSelectionsCountAggregateOutputType | null
  _min: FeatureSelectionsMinAggregateOutputType | null
  _max: FeatureSelectionsMaxAggregateOutputType | null
}

type GetFeatureSelectionsGroupByPayload<T extends FeatureSelectionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FeatureSelectionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FeatureSelectionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FeatureSelectionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FeatureSelectionsGroupByOutputType[P]>
      }
    >
  >



export type FeatureSelectionsWhereInput = {
  AND?: Prisma.FeatureSelectionsWhereInput | Prisma.FeatureSelectionsWhereInput[]
  OR?: Prisma.FeatureSelectionsWhereInput[]
  NOT?: Prisma.FeatureSelectionsWhereInput | Prisma.FeatureSelectionsWhereInput[]
  id?: Prisma.StringFilter<"FeatureSelections"> | string
  userId?: Prisma.StringFilter<"FeatureSelections"> | string
  calendar?: Prisma.BoolFilter<"FeatureSelections"> | boolean
  journal?: Prisma.BoolFilter<"FeatureSelections"> | boolean
  aiWorkout?: Prisma.BoolFilter<"FeatureSelections"> | boolean
  sleep?: Prisma.BoolFilter<"FeatureSelections"> | boolean
  createdAt?: Prisma.DateTimeFilter<"FeatureSelections"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type FeatureSelectionsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  calendar?: Prisma.SortOrder
  journal?: Prisma.SortOrder
  aiWorkout?: Prisma.SortOrder
  sleep?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type FeatureSelectionsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FeatureSelectionsWhereInput | Prisma.FeatureSelectionsWhereInput[]
  OR?: Prisma.FeatureSelectionsWhereInput[]
  NOT?: Prisma.FeatureSelectionsWhereInput | Prisma.FeatureSelectionsWhereInput[]
  userId?: Prisma.StringFilter<"FeatureSelections"> | string
  calendar?: Prisma.BoolFilter<"FeatureSelections"> | boolean
  journal?: Prisma.BoolFilter<"FeatureSelections"> | boolean
  aiWorkout?: Prisma.BoolFilter<"FeatureSelections"> | boolean
  sleep?: Prisma.BoolFilter<"FeatureSelections"> | boolean
  createdAt?: Prisma.DateTimeFilter<"FeatureSelections"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type FeatureSelectionsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  calendar?: Prisma.SortOrder
  journal?: Prisma.SortOrder
  aiWorkout?: Prisma.SortOrder
  sleep?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.FeatureSelectionsCountOrderByAggregateInput
  _max?: Prisma.FeatureSelectionsMaxOrderByAggregateInput
  _min?: Prisma.FeatureSelectionsMinOrderByAggregateInput
}

export type FeatureSelectionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.FeatureSelectionsScalarWhereWithAggregatesInput | Prisma.FeatureSelectionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.FeatureSelectionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FeatureSelectionsScalarWhereWithAggregatesInput | Prisma.FeatureSelectionsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FeatureSelections"> | string
  userId?: Prisma.StringWithAggregatesFilter<"FeatureSelections"> | string
  calendar?: Prisma.BoolWithAggregatesFilter<"FeatureSelections"> | boolean
  journal?: Prisma.BoolWithAggregatesFilter<"FeatureSelections"> | boolean
  aiWorkout?: Prisma.BoolWithAggregatesFilter<"FeatureSelections"> | boolean
  sleep?: Prisma.BoolWithAggregatesFilter<"FeatureSelections"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FeatureSelections"> | Date | string
}

export type FeatureSelectionsCreateInput = {
  id?: string
  calendar?: boolean
  journal?: boolean
  aiWorkout?: boolean
  sleep?: boolean
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutFeatureSelectionsInput
}

export type FeatureSelectionsUncheckedCreateInput = {
  id?: string
  userId: string
  calendar?: boolean
  journal?: boolean
  aiWorkout?: boolean
  sleep?: boolean
  createdAt?: Date | string
}

export type FeatureSelectionsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  calendar?: Prisma.BoolFieldUpdateOperationsInput | boolean
  journal?: Prisma.BoolFieldUpdateOperationsInput | boolean
  aiWorkout?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sleep?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutFeatureSelectionsNestedInput
}

export type FeatureSelectionsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  calendar?: Prisma.BoolFieldUpdateOperationsInput | boolean
  journal?: Prisma.BoolFieldUpdateOperationsInput | boolean
  aiWorkout?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sleep?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeatureSelectionsCreateManyInput = {
  id?: string
  userId: string
  calendar?: boolean
  journal?: boolean
  aiWorkout?: boolean
  sleep?: boolean
  createdAt?: Date | string
}

export type FeatureSelectionsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  calendar?: Prisma.BoolFieldUpdateOperationsInput | boolean
  journal?: Prisma.BoolFieldUpdateOperationsInput | boolean
  aiWorkout?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sleep?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeatureSelectionsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  calendar?: Prisma.BoolFieldUpdateOperationsInput | boolean
  journal?: Prisma.BoolFieldUpdateOperationsInput | boolean
  aiWorkout?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sleep?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeatureSelectionsListRelationFilter = {
  every?: Prisma.FeatureSelectionsWhereInput
  some?: Prisma.FeatureSelectionsWhereInput
  none?: Prisma.FeatureSelectionsWhereInput
}

export type FeatureSelectionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FeatureSelectionsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  calendar?: Prisma.SortOrder
  journal?: Prisma.SortOrder
  aiWorkout?: Prisma.SortOrder
  sleep?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FeatureSelectionsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  calendar?: Prisma.SortOrder
  journal?: Prisma.SortOrder
  aiWorkout?: Prisma.SortOrder
  sleep?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FeatureSelectionsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  calendar?: Prisma.SortOrder
  journal?: Prisma.SortOrder
  aiWorkout?: Prisma.SortOrder
  sleep?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FeatureSelectionsCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FeatureSelectionsCreateWithoutUserInput, Prisma.FeatureSelectionsUncheckedCreateWithoutUserInput> | Prisma.FeatureSelectionsCreateWithoutUserInput[] | Prisma.FeatureSelectionsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FeatureSelectionsCreateOrConnectWithoutUserInput | Prisma.FeatureSelectionsCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.FeatureSelectionsCreateManyUserInputEnvelope
  connect?: Prisma.FeatureSelectionsWhereUniqueInput | Prisma.FeatureSelectionsWhereUniqueInput[]
}

export type FeatureSelectionsUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FeatureSelectionsCreateWithoutUserInput, Prisma.FeatureSelectionsUncheckedCreateWithoutUserInput> | Prisma.FeatureSelectionsCreateWithoutUserInput[] | Prisma.FeatureSelectionsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FeatureSelectionsCreateOrConnectWithoutUserInput | Prisma.FeatureSelectionsCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.FeatureSelectionsCreateManyUserInputEnvelope
  connect?: Prisma.FeatureSelectionsWhereUniqueInput | Prisma.FeatureSelectionsWhereUniqueInput[]
}

export type FeatureSelectionsUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FeatureSelectionsCreateWithoutUserInput, Prisma.FeatureSelectionsUncheckedCreateWithoutUserInput> | Prisma.FeatureSelectionsCreateWithoutUserInput[] | Prisma.FeatureSelectionsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FeatureSelectionsCreateOrConnectWithoutUserInput | Prisma.FeatureSelectionsCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.FeatureSelectionsUpsertWithWhereUniqueWithoutUserInput | Prisma.FeatureSelectionsUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.FeatureSelectionsCreateManyUserInputEnvelope
  set?: Prisma.FeatureSelectionsWhereUniqueInput | Prisma.FeatureSelectionsWhereUniqueInput[]
  disconnect?: Prisma.FeatureSelectionsWhereUniqueInput | Prisma.FeatureSelectionsWhereUniqueInput[]
  delete?: Prisma.FeatureSelectionsWhereUniqueInput | Prisma.FeatureSelectionsWhereUniqueInput[]
  connect?: Prisma.FeatureSelectionsWhereUniqueInput | Prisma.FeatureSelectionsWhereUniqueInput[]
  update?: Prisma.FeatureSelectionsUpdateWithWhereUniqueWithoutUserInput | Prisma.FeatureSelectionsUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.FeatureSelectionsUpdateManyWithWhereWithoutUserInput | Prisma.FeatureSelectionsUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.FeatureSelectionsScalarWhereInput | Prisma.FeatureSelectionsScalarWhereInput[]
}

export type FeatureSelectionsUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FeatureSelectionsCreateWithoutUserInput, Prisma.FeatureSelectionsUncheckedCreateWithoutUserInput> | Prisma.FeatureSelectionsCreateWithoutUserInput[] | Prisma.FeatureSelectionsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FeatureSelectionsCreateOrConnectWithoutUserInput | Prisma.FeatureSelectionsCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.FeatureSelectionsUpsertWithWhereUniqueWithoutUserInput | Prisma.FeatureSelectionsUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.FeatureSelectionsCreateManyUserInputEnvelope
  set?: Prisma.FeatureSelectionsWhereUniqueInput | Prisma.FeatureSelectionsWhereUniqueInput[]
  disconnect?: Prisma.FeatureSelectionsWhereUniqueInput | Prisma.FeatureSelectionsWhereUniqueInput[]
  delete?: Prisma.FeatureSelectionsWhereUniqueInput | Prisma.FeatureSelectionsWhereUniqueInput[]
  connect?: Prisma.FeatureSelectionsWhereUniqueInput | Prisma.FeatureSelectionsWhereUniqueInput[]
  update?: Prisma.FeatureSelectionsUpdateWithWhereUniqueWithoutUserInput | Prisma.FeatureSelectionsUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.FeatureSelectionsUpdateManyWithWhereWithoutUserInput | Prisma.FeatureSelectionsUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.FeatureSelectionsScalarWhereInput | Prisma.FeatureSelectionsScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type FeatureSelectionsCreateWithoutUserInput = {
  id?: string
  calendar?: boolean
  journal?: boolean
  aiWorkout?: boolean
  sleep?: boolean
  createdAt?: Date | string
}

export type FeatureSelectionsUncheckedCreateWithoutUserInput = {
  id?: string
  calendar?: boolean
  journal?: boolean
  aiWorkout?: boolean
  sleep?: boolean
  createdAt?: Date | string
}

export type FeatureSelectionsCreateOrConnectWithoutUserInput = {
  where: Prisma.FeatureSelectionsWhereUniqueInput
  create: Prisma.XOR<Prisma.FeatureSelectionsCreateWithoutUserInput, Prisma.FeatureSelectionsUncheckedCreateWithoutUserInput>
}

export type FeatureSelectionsCreateManyUserInputEnvelope = {
  data: Prisma.FeatureSelectionsCreateManyUserInput | Prisma.FeatureSelectionsCreateManyUserInput[]
}

export type FeatureSelectionsUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.FeatureSelectionsWhereUniqueInput
  update: Prisma.XOR<Prisma.FeatureSelectionsUpdateWithoutUserInput, Prisma.FeatureSelectionsUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.FeatureSelectionsCreateWithoutUserInput, Prisma.FeatureSelectionsUncheckedCreateWithoutUserInput>
}

export type FeatureSelectionsUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.FeatureSelectionsWhereUniqueInput
  data: Prisma.XOR<Prisma.FeatureSelectionsUpdateWithoutUserInput, Prisma.FeatureSelectionsUncheckedUpdateWithoutUserInput>
}

export type FeatureSelectionsUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.FeatureSelectionsScalarWhereInput
  data: Prisma.XOR<Prisma.FeatureSelectionsUpdateManyMutationInput, Prisma.FeatureSelectionsUncheckedUpdateManyWithoutUserInput>
}

export type FeatureSelectionsScalarWhereInput = {
  AND?: Prisma.FeatureSelectionsScalarWhereInput | Prisma.FeatureSelectionsScalarWhereInput[]
  OR?: Prisma.FeatureSelectionsScalarWhereInput[]
  NOT?: Prisma.FeatureSelectionsScalarWhereInput | Prisma.FeatureSelectionsScalarWhereInput[]
  id?: Prisma.StringFilter<"FeatureSelections"> | string
  userId?: Prisma.StringFilter<"FeatureSelections"> | string
  calendar?: Prisma.BoolFilter<"FeatureSelections"> | boolean
  journal?: Prisma.BoolFilter<"FeatureSelections"> | boolean
  aiWorkout?: Prisma.BoolFilter<"FeatureSelections"> | boolean
  sleep?: Prisma.BoolFilter<"FeatureSelections"> | boolean
  createdAt?: Prisma.DateTimeFilter<"FeatureSelections"> | Date | string
}

export type FeatureSelectionsCreateManyUserInput = {
  id?: string
  calendar?: boolean
  journal?: boolean
  aiWorkout?: boolean
  sleep?: boolean
  createdAt?: Date | string
}

export type FeatureSelectionsUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  calendar?: Prisma.BoolFieldUpdateOperationsInput | boolean
  journal?: Prisma.BoolFieldUpdateOperationsInput | boolean
  aiWorkout?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sleep?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeatureSelectionsUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  calendar?: Prisma.BoolFieldUpdateOperationsInput | boolean
  journal?: Prisma.BoolFieldUpdateOperationsInput | boolean
  aiWorkout?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sleep?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FeatureSelectionsUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  calendar?: Prisma.BoolFieldUpdateOperationsInput | boolean
  journal?: Prisma.BoolFieldUpdateOperationsInput | boolean
  aiWorkout?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sleep?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type FeatureSelectionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  calendar?: boolean
  journal?: boolean
  aiWorkout?: boolean
  sleep?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["featureSelections"]>

export type FeatureSelectionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  calendar?: boolean
  journal?: boolean
  aiWorkout?: boolean
  sleep?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["featureSelections"]>

export type FeatureSelectionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  calendar?: boolean
  journal?: boolean
  aiWorkout?: boolean
  sleep?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["featureSelections"]>

export type FeatureSelectionsSelectScalar = {
  id?: boolean
  userId?: boolean
  calendar?: boolean
  journal?: boolean
  aiWorkout?: boolean
  sleep?: boolean
  createdAt?: boolean
}

export type FeatureSelectionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "calendar" | "journal" | "aiWorkout" | "sleep" | "createdAt", ExtArgs["result"]["featureSelections"]>
export type FeatureSelectionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type FeatureSelectionsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type FeatureSelectionsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $FeatureSelectionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FeatureSelections"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    calendar: boolean
    journal: boolean
    aiWorkout: boolean
    sleep: boolean
    createdAt: Date
  }, ExtArgs["result"]["featureSelections"]>
  composites: {}
}

export type FeatureSelectionsGetPayload<S extends boolean | null | undefined | FeatureSelectionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FeatureSelectionsPayload, S>

export type FeatureSelectionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FeatureSelectionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FeatureSelectionsCountAggregateInputType | true
  }

export interface FeatureSelectionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FeatureSelections'], meta: { name: 'FeatureSelections' } }
  /**
   * Find zero or one FeatureSelections that matches the filter.
   * @param {FeatureSelectionsFindUniqueArgs} args - Arguments to find a FeatureSelections
   * @example
   * // Get one FeatureSelections
   * const featureSelections = await prisma.featureSelections.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FeatureSelectionsFindUniqueArgs>(args: Prisma.SelectSubset<T, FeatureSelectionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FeatureSelectionsClient<runtime.Types.Result.GetResult<Prisma.$FeatureSelectionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FeatureSelections that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FeatureSelectionsFindUniqueOrThrowArgs} args - Arguments to find a FeatureSelections
   * @example
   * // Get one FeatureSelections
   * const featureSelections = await prisma.featureSelections.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FeatureSelectionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FeatureSelectionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FeatureSelectionsClient<runtime.Types.Result.GetResult<Prisma.$FeatureSelectionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FeatureSelections that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeatureSelectionsFindFirstArgs} args - Arguments to find a FeatureSelections
   * @example
   * // Get one FeatureSelections
   * const featureSelections = await prisma.featureSelections.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FeatureSelectionsFindFirstArgs>(args?: Prisma.SelectSubset<T, FeatureSelectionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__FeatureSelectionsClient<runtime.Types.Result.GetResult<Prisma.$FeatureSelectionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FeatureSelections that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeatureSelectionsFindFirstOrThrowArgs} args - Arguments to find a FeatureSelections
   * @example
   * // Get one FeatureSelections
   * const featureSelections = await prisma.featureSelections.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FeatureSelectionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FeatureSelectionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FeatureSelectionsClient<runtime.Types.Result.GetResult<Prisma.$FeatureSelectionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FeatureSelections that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeatureSelectionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FeatureSelections
   * const featureSelections = await prisma.featureSelections.findMany()
   * 
   * // Get first 10 FeatureSelections
   * const featureSelections = await prisma.featureSelections.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const featureSelectionsWithIdOnly = await prisma.featureSelections.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FeatureSelectionsFindManyArgs>(args?: Prisma.SelectSubset<T, FeatureSelectionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeatureSelectionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FeatureSelections.
   * @param {FeatureSelectionsCreateArgs} args - Arguments to create a FeatureSelections.
   * @example
   * // Create one FeatureSelections
   * const FeatureSelections = await prisma.featureSelections.create({
   *   data: {
   *     // ... data to create a FeatureSelections
   *   }
   * })
   * 
   */
  create<T extends FeatureSelectionsCreateArgs>(args: Prisma.SelectSubset<T, FeatureSelectionsCreateArgs<ExtArgs>>): Prisma.Prisma__FeatureSelectionsClient<runtime.Types.Result.GetResult<Prisma.$FeatureSelectionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FeatureSelections.
   * @param {FeatureSelectionsCreateManyArgs} args - Arguments to create many FeatureSelections.
   * @example
   * // Create many FeatureSelections
   * const featureSelections = await prisma.featureSelections.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FeatureSelectionsCreateManyArgs>(args?: Prisma.SelectSubset<T, FeatureSelectionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FeatureSelections and returns the data saved in the database.
   * @param {FeatureSelectionsCreateManyAndReturnArgs} args - Arguments to create many FeatureSelections.
   * @example
   * // Create many FeatureSelections
   * const featureSelections = await prisma.featureSelections.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FeatureSelections and only return the `id`
   * const featureSelectionsWithIdOnly = await prisma.featureSelections.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FeatureSelectionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FeatureSelectionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeatureSelectionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FeatureSelections.
   * @param {FeatureSelectionsDeleteArgs} args - Arguments to delete one FeatureSelections.
   * @example
   * // Delete one FeatureSelections
   * const FeatureSelections = await prisma.featureSelections.delete({
   *   where: {
   *     // ... filter to delete one FeatureSelections
   *   }
   * })
   * 
   */
  delete<T extends FeatureSelectionsDeleteArgs>(args: Prisma.SelectSubset<T, FeatureSelectionsDeleteArgs<ExtArgs>>): Prisma.Prisma__FeatureSelectionsClient<runtime.Types.Result.GetResult<Prisma.$FeatureSelectionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FeatureSelections.
   * @param {FeatureSelectionsUpdateArgs} args - Arguments to update one FeatureSelections.
   * @example
   * // Update one FeatureSelections
   * const featureSelections = await prisma.featureSelections.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FeatureSelectionsUpdateArgs>(args: Prisma.SelectSubset<T, FeatureSelectionsUpdateArgs<ExtArgs>>): Prisma.Prisma__FeatureSelectionsClient<runtime.Types.Result.GetResult<Prisma.$FeatureSelectionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FeatureSelections.
   * @param {FeatureSelectionsDeleteManyArgs} args - Arguments to filter FeatureSelections to delete.
   * @example
   * // Delete a few FeatureSelections
   * const { count } = await prisma.featureSelections.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FeatureSelectionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, FeatureSelectionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FeatureSelections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeatureSelectionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FeatureSelections
   * const featureSelections = await prisma.featureSelections.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FeatureSelectionsUpdateManyArgs>(args: Prisma.SelectSubset<T, FeatureSelectionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FeatureSelections and returns the data updated in the database.
   * @param {FeatureSelectionsUpdateManyAndReturnArgs} args - Arguments to update many FeatureSelections.
   * @example
   * // Update many FeatureSelections
   * const featureSelections = await prisma.featureSelections.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FeatureSelections and only return the `id`
   * const featureSelectionsWithIdOnly = await prisma.featureSelections.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FeatureSelectionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FeatureSelectionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeatureSelectionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FeatureSelections.
   * @param {FeatureSelectionsUpsertArgs} args - Arguments to update or create a FeatureSelections.
   * @example
   * // Update or create a FeatureSelections
   * const featureSelections = await prisma.featureSelections.upsert({
   *   create: {
   *     // ... data to create a FeatureSelections
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FeatureSelections we want to update
   *   }
   * })
   */
  upsert<T extends FeatureSelectionsUpsertArgs>(args: Prisma.SelectSubset<T, FeatureSelectionsUpsertArgs<ExtArgs>>): Prisma.Prisma__FeatureSelectionsClient<runtime.Types.Result.GetResult<Prisma.$FeatureSelectionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FeatureSelections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeatureSelectionsCountArgs} args - Arguments to filter FeatureSelections to count.
   * @example
   * // Count the number of FeatureSelections
   * const count = await prisma.featureSelections.count({
   *   where: {
   *     // ... the filter for the FeatureSelections we want to count
   *   }
   * })
  **/
  count<T extends FeatureSelectionsCountArgs>(
    args?: Prisma.Subset<T, FeatureSelectionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FeatureSelectionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FeatureSelections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeatureSelectionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FeatureSelectionsAggregateArgs>(args: Prisma.Subset<T, FeatureSelectionsAggregateArgs>): Prisma.PrismaPromise<GetFeatureSelectionsAggregateType<T>>

  /**
   * Group by FeatureSelections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FeatureSelectionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FeatureSelectionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FeatureSelectionsGroupByArgs['orderBy'] }
      : { orderBy?: FeatureSelectionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FeatureSelectionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFeatureSelectionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FeatureSelections model
 */
readonly fields: FeatureSelectionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FeatureSelections.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FeatureSelectionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FeatureSelections model
 */
export interface FeatureSelectionsFieldRefs {
  readonly id: Prisma.FieldRef<"FeatureSelections", 'String'>
  readonly userId: Prisma.FieldRef<"FeatureSelections", 'String'>
  readonly calendar: Prisma.FieldRef<"FeatureSelections", 'Boolean'>
  readonly journal: Prisma.FieldRef<"FeatureSelections", 'Boolean'>
  readonly aiWorkout: Prisma.FieldRef<"FeatureSelections", 'Boolean'>
  readonly sleep: Prisma.FieldRef<"FeatureSelections", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"FeatureSelections", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FeatureSelections findUnique
 */
export type FeatureSelectionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeatureSelections
   */
  select?: Prisma.FeatureSelectionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeatureSelections
   */
  omit?: Prisma.FeatureSelectionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeatureSelectionsInclude<ExtArgs> | null
  /**
   * Filter, which FeatureSelections to fetch.
   */
  where: Prisma.FeatureSelectionsWhereUniqueInput
}

/**
 * FeatureSelections findUniqueOrThrow
 */
export type FeatureSelectionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeatureSelections
   */
  select?: Prisma.FeatureSelectionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeatureSelections
   */
  omit?: Prisma.FeatureSelectionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeatureSelectionsInclude<ExtArgs> | null
  /**
   * Filter, which FeatureSelections to fetch.
   */
  where: Prisma.FeatureSelectionsWhereUniqueInput
}

/**
 * FeatureSelections findFirst
 */
export type FeatureSelectionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeatureSelections
   */
  select?: Prisma.FeatureSelectionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeatureSelections
   */
  omit?: Prisma.FeatureSelectionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeatureSelectionsInclude<ExtArgs> | null
  /**
   * Filter, which FeatureSelections to fetch.
   */
  where?: Prisma.FeatureSelectionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeatureSelections to fetch.
   */
  orderBy?: Prisma.FeatureSelectionsOrderByWithRelationInput | Prisma.FeatureSelectionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FeatureSelections.
   */
  cursor?: Prisma.FeatureSelectionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeatureSelections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeatureSelections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FeatureSelections.
   */
  distinct?: Prisma.FeatureSelectionsScalarFieldEnum | Prisma.FeatureSelectionsScalarFieldEnum[]
}

/**
 * FeatureSelections findFirstOrThrow
 */
export type FeatureSelectionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeatureSelections
   */
  select?: Prisma.FeatureSelectionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeatureSelections
   */
  omit?: Prisma.FeatureSelectionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeatureSelectionsInclude<ExtArgs> | null
  /**
   * Filter, which FeatureSelections to fetch.
   */
  where?: Prisma.FeatureSelectionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeatureSelections to fetch.
   */
  orderBy?: Prisma.FeatureSelectionsOrderByWithRelationInput | Prisma.FeatureSelectionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FeatureSelections.
   */
  cursor?: Prisma.FeatureSelectionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeatureSelections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeatureSelections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FeatureSelections.
   */
  distinct?: Prisma.FeatureSelectionsScalarFieldEnum | Prisma.FeatureSelectionsScalarFieldEnum[]
}

/**
 * FeatureSelections findMany
 */
export type FeatureSelectionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeatureSelections
   */
  select?: Prisma.FeatureSelectionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeatureSelections
   */
  omit?: Prisma.FeatureSelectionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeatureSelectionsInclude<ExtArgs> | null
  /**
   * Filter, which FeatureSelections to fetch.
   */
  where?: Prisma.FeatureSelectionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FeatureSelections to fetch.
   */
  orderBy?: Prisma.FeatureSelectionsOrderByWithRelationInput | Prisma.FeatureSelectionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FeatureSelections.
   */
  cursor?: Prisma.FeatureSelectionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FeatureSelections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FeatureSelections.
   */
  skip?: number
  distinct?: Prisma.FeatureSelectionsScalarFieldEnum | Prisma.FeatureSelectionsScalarFieldEnum[]
}

/**
 * FeatureSelections create
 */
export type FeatureSelectionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeatureSelections
   */
  select?: Prisma.FeatureSelectionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeatureSelections
   */
  omit?: Prisma.FeatureSelectionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeatureSelectionsInclude<ExtArgs> | null
  /**
   * The data needed to create a FeatureSelections.
   */
  data: Prisma.XOR<Prisma.FeatureSelectionsCreateInput, Prisma.FeatureSelectionsUncheckedCreateInput>
}

/**
 * FeatureSelections createMany
 */
export type FeatureSelectionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FeatureSelections.
   */
  data: Prisma.FeatureSelectionsCreateManyInput | Prisma.FeatureSelectionsCreateManyInput[]
}

/**
 * FeatureSelections createManyAndReturn
 */
export type FeatureSelectionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeatureSelections
   */
  select?: Prisma.FeatureSelectionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FeatureSelections
   */
  omit?: Prisma.FeatureSelectionsOmit<ExtArgs> | null
  /**
   * The data used to create many FeatureSelections.
   */
  data: Prisma.FeatureSelectionsCreateManyInput | Prisma.FeatureSelectionsCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeatureSelectionsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FeatureSelections update
 */
export type FeatureSelectionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeatureSelections
   */
  select?: Prisma.FeatureSelectionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeatureSelections
   */
  omit?: Prisma.FeatureSelectionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeatureSelectionsInclude<ExtArgs> | null
  /**
   * The data needed to update a FeatureSelections.
   */
  data: Prisma.XOR<Prisma.FeatureSelectionsUpdateInput, Prisma.FeatureSelectionsUncheckedUpdateInput>
  /**
   * Choose, which FeatureSelections to update.
   */
  where: Prisma.FeatureSelectionsWhereUniqueInput
}

/**
 * FeatureSelections updateMany
 */
export type FeatureSelectionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FeatureSelections.
   */
  data: Prisma.XOR<Prisma.FeatureSelectionsUpdateManyMutationInput, Prisma.FeatureSelectionsUncheckedUpdateManyInput>
  /**
   * Filter which FeatureSelections to update
   */
  where?: Prisma.FeatureSelectionsWhereInput
  /**
   * Limit how many FeatureSelections to update.
   */
  limit?: number
}

/**
 * FeatureSelections updateManyAndReturn
 */
export type FeatureSelectionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeatureSelections
   */
  select?: Prisma.FeatureSelectionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FeatureSelections
   */
  omit?: Prisma.FeatureSelectionsOmit<ExtArgs> | null
  /**
   * The data used to update FeatureSelections.
   */
  data: Prisma.XOR<Prisma.FeatureSelectionsUpdateManyMutationInput, Prisma.FeatureSelectionsUncheckedUpdateManyInput>
  /**
   * Filter which FeatureSelections to update
   */
  where?: Prisma.FeatureSelectionsWhereInput
  /**
   * Limit how many FeatureSelections to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeatureSelectionsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FeatureSelections upsert
 */
export type FeatureSelectionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeatureSelections
   */
  select?: Prisma.FeatureSelectionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeatureSelections
   */
  omit?: Prisma.FeatureSelectionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeatureSelectionsInclude<ExtArgs> | null
  /**
   * The filter to search for the FeatureSelections to update in case it exists.
   */
  where: Prisma.FeatureSelectionsWhereUniqueInput
  /**
   * In case the FeatureSelections found by the `where` argument doesn't exist, create a new FeatureSelections with this data.
   */
  create: Prisma.XOR<Prisma.FeatureSelectionsCreateInput, Prisma.FeatureSelectionsUncheckedCreateInput>
  /**
   * In case the FeatureSelections was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FeatureSelectionsUpdateInput, Prisma.FeatureSelectionsUncheckedUpdateInput>
}

/**
 * FeatureSelections delete
 */
export type FeatureSelectionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeatureSelections
   */
  select?: Prisma.FeatureSelectionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeatureSelections
   */
  omit?: Prisma.FeatureSelectionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeatureSelectionsInclude<ExtArgs> | null
  /**
   * Filter which FeatureSelections to delete.
   */
  where: Prisma.FeatureSelectionsWhereUniqueInput
}

/**
 * FeatureSelections deleteMany
 */
export type FeatureSelectionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FeatureSelections to delete
   */
  where?: Prisma.FeatureSelectionsWhereInput
  /**
   * Limit how many FeatureSelections to delete.
   */
  limit?: number
}

/**
 * FeatureSelections without action
 */
export type FeatureSelectionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeatureSelections
   */
  select?: Prisma.FeatureSelectionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeatureSelections
   */
  omit?: Prisma.FeatureSelectionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeatureSelectionsInclude<ExtArgs> | null
}
