
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `User` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model User
 * 
 */
export type UserModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPayload>

export type AggregateUser = {
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type UserMinAggregateOutputType = {
  id: string | null
  email: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserMaxAggregateOutputType = {
  id: string | null
  email: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type UserCountAggregateOutputType = {
  id: number
  email: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type UserMinAggregateInputType = {
  id?: true
  email?: true
  createdAt?: true
  updatedAt?: true
}

export type UserMaxAggregateInputType = {
  id?: true
  email?: true
  createdAt?: true
  updatedAt?: true
}

export type UserCountAggregateInputType = {
  id?: true
  email?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type UserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which User to aggregate.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMaxAggregateInputType
}

export type GetUserAggregateType<T extends UserAggregateArgs> = {
      [P in keyof T & keyof AggregateUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser[P]>
    : Prisma.GetScalarType<T[P], AggregateUser[P]>
}




export type UserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithAggregationInput | Prisma.UserOrderByWithAggregationInput[]
  by: Prisma.UserScalarFieldEnum[] | Prisma.UserScalarFieldEnum
  having?: Prisma.UserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCountAggregateInputType | true
  _min?: UserMinAggregateInputType
  _max?: UserMaxAggregateInputType
}

export type UserGroupByOutputType = {
  id: string
  email: string | null
  createdAt: Date
  updatedAt: Date
  _count: UserCountAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

type GetUserGroupByPayload<T extends UserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
      }
    >
  >



export type UserWhereInput = {
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  id?: Prisma.StringFilter<"User"> | string
  email?: Prisma.StringNullableFilter<"User"> | string | null
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string
  featureSelections?: Prisma.FeatureSelectionsListRelationFilter
  journalEntries?: Prisma.JournalEntryListRelationFilter
  workoutLogs?: Prisma.WorkoutLogListRelationFilter
  calendarItems?: Prisma.CalendarItemListRelationFilter
  sleepLogs?: Prisma.SleepLogListRelationFilter
  analyzerFindings?: Prisma.AnalyzerFindingListRelationFilter
  aiWorkouts?: Prisma.AiWorkoutPlanListRelationFilter
}

export type UserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  featureSelections?: Prisma.FeatureSelectionsOrderByRelationAggregateInput
  journalEntries?: Prisma.JournalEntryOrderByRelationAggregateInput
  workoutLogs?: Prisma.WorkoutLogOrderByRelationAggregateInput
  calendarItems?: Prisma.CalendarItemOrderByRelationAggregateInput
  sleepLogs?: Prisma.SleepLogOrderByRelationAggregateInput
  analyzerFindings?: Prisma.AnalyzerFindingOrderByRelationAggregateInput
  aiWorkouts?: Prisma.AiWorkoutPlanOrderByRelationAggregateInput
}

export type UserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string
  featureSelections?: Prisma.FeatureSelectionsListRelationFilter
  journalEntries?: Prisma.JournalEntryListRelationFilter
  workoutLogs?: Prisma.WorkoutLogListRelationFilter
  calendarItems?: Prisma.CalendarItemListRelationFilter
  sleepLogs?: Prisma.SleepLogListRelationFilter
  analyzerFindings?: Prisma.AnalyzerFindingListRelationFilter
  aiWorkouts?: Prisma.AiWorkoutPlanListRelationFilter
}, "id" | "email">

export type UserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.UserCountOrderByAggregateInput
  _max?: Prisma.UserMaxOrderByAggregateInput
  _min?: Prisma.UserMinOrderByAggregateInput
}

export type UserScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"User"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
}

export type UserCreateInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  featureSelections?: Prisma.FeatureSelectionsCreateNestedManyWithoutUserInput
  journalEntries?: Prisma.JournalEntryCreateNestedManyWithoutUserInput
  workoutLogs?: Prisma.WorkoutLogCreateNestedManyWithoutUserInput
  calendarItems?: Prisma.CalendarItemCreateNestedManyWithoutUserInput
  sleepLogs?: Prisma.SleepLogCreateNestedManyWithoutUserInput
  analyzerFindings?: Prisma.AnalyzerFindingCreateNestedManyWithoutUserInput
  aiWorkouts?: Prisma.AiWorkoutPlanCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  featureSelections?: Prisma.FeatureSelectionsUncheckedCreateNestedManyWithoutUserInput
  journalEntries?: Prisma.JournalEntryUncheckedCreateNestedManyWithoutUserInput
  workoutLogs?: Prisma.WorkoutLogUncheckedCreateNestedManyWithoutUserInput
  calendarItems?: Prisma.CalendarItemUncheckedCreateNestedManyWithoutUserInput
  sleepLogs?: Prisma.SleepLogUncheckedCreateNestedManyWithoutUserInput
  analyzerFindings?: Prisma.AnalyzerFindingUncheckedCreateNestedManyWithoutUserInput
  aiWorkouts?: Prisma.AiWorkoutPlanUncheckedCreateNestedManyWithoutUserInput
}

export type UserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  featureSelections?: Prisma.FeatureSelectionsUpdateManyWithoutUserNestedInput
  journalEntries?: Prisma.JournalEntryUpdateManyWithoutUserNestedInput
  workoutLogs?: Prisma.WorkoutLogUpdateManyWithoutUserNestedInput
  calendarItems?: Prisma.CalendarItemUpdateManyWithoutUserNestedInput
  sleepLogs?: Prisma.SleepLogUpdateManyWithoutUserNestedInput
  analyzerFindings?: Prisma.AnalyzerFindingUpdateManyWithoutUserNestedInput
  aiWorkouts?: Prisma.AiWorkoutPlanUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  featureSelections?: Prisma.FeatureSelectionsUncheckedUpdateManyWithoutUserNestedInput
  journalEntries?: Prisma.JournalEntryUncheckedUpdateManyWithoutUserNestedInput
  workoutLogs?: Prisma.WorkoutLogUncheckedUpdateManyWithoutUserNestedInput
  calendarItems?: Prisma.CalendarItemUncheckedUpdateManyWithoutUserNestedInput
  sleepLogs?: Prisma.SleepLogUncheckedUpdateManyWithoutUserNestedInput
  analyzerFindings?: Prisma.AnalyzerFindingUncheckedUpdateManyWithoutUserNestedInput
  aiWorkouts?: Prisma.AiWorkoutPlanUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateManyInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type UserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  email?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type UserScalarRelationFilter = {
  is?: Prisma.UserWhereInput
  isNot?: Prisma.UserWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type UserCreateNestedOneWithoutFeatureSelectionsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutFeatureSelectionsInput, Prisma.UserUncheckedCreateWithoutFeatureSelectionsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutFeatureSelectionsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutFeatureSelectionsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutFeatureSelectionsInput, Prisma.UserUncheckedCreateWithoutFeatureSelectionsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutFeatureSelectionsInput
  upsert?: Prisma.UserUpsertWithoutFeatureSelectionsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutFeatureSelectionsInput, Prisma.UserUpdateWithoutFeatureSelectionsInput>, Prisma.UserUncheckedUpdateWithoutFeatureSelectionsInput>
}

export type UserCreateNestedOneWithoutJournalEntriesInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutJournalEntriesInput, Prisma.UserUncheckedCreateWithoutJournalEntriesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutJournalEntriesInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutJournalEntriesNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutJournalEntriesInput, Prisma.UserUncheckedCreateWithoutJournalEntriesInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutJournalEntriesInput
  upsert?: Prisma.UserUpsertWithoutJournalEntriesInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutJournalEntriesInput, Prisma.UserUpdateWithoutJournalEntriesInput>, Prisma.UserUncheckedUpdateWithoutJournalEntriesInput>
}

export type UserCreateNestedOneWithoutWorkoutLogsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutWorkoutLogsInput, Prisma.UserUncheckedCreateWithoutWorkoutLogsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutWorkoutLogsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutWorkoutLogsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutWorkoutLogsInput, Prisma.UserUncheckedCreateWithoutWorkoutLogsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutWorkoutLogsInput
  upsert?: Prisma.UserUpsertWithoutWorkoutLogsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutWorkoutLogsInput, Prisma.UserUpdateWithoutWorkoutLogsInput>, Prisma.UserUncheckedUpdateWithoutWorkoutLogsInput>
}

export type UserCreateNestedOneWithoutCalendarItemsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCalendarItemsInput, Prisma.UserUncheckedCreateWithoutCalendarItemsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCalendarItemsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutCalendarItemsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCalendarItemsInput, Prisma.UserUncheckedCreateWithoutCalendarItemsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCalendarItemsInput
  upsert?: Prisma.UserUpsertWithoutCalendarItemsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutCalendarItemsInput, Prisma.UserUpdateWithoutCalendarItemsInput>, Prisma.UserUncheckedUpdateWithoutCalendarItemsInput>
}

export type UserCreateNestedOneWithoutSleepLogsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutSleepLogsInput, Prisma.UserUncheckedCreateWithoutSleepLogsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutSleepLogsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutSleepLogsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutSleepLogsInput, Prisma.UserUncheckedCreateWithoutSleepLogsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutSleepLogsInput
  upsert?: Prisma.UserUpsertWithoutSleepLogsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutSleepLogsInput, Prisma.UserUpdateWithoutSleepLogsInput>, Prisma.UserUncheckedUpdateWithoutSleepLogsInput>
}

export type UserCreateNestedOneWithoutAnalyzerFindingsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutAnalyzerFindingsInput, Prisma.UserUncheckedCreateWithoutAnalyzerFindingsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutAnalyzerFindingsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutAnalyzerFindingsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutAnalyzerFindingsInput, Prisma.UserUncheckedCreateWithoutAnalyzerFindingsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutAnalyzerFindingsInput
  upsert?: Prisma.UserUpsertWithoutAnalyzerFindingsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutAnalyzerFindingsInput, Prisma.UserUpdateWithoutAnalyzerFindingsInput>, Prisma.UserUncheckedUpdateWithoutAnalyzerFindingsInput>
}

export type UserCreateNestedOneWithoutAiWorkoutsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutAiWorkoutsInput, Prisma.UserUncheckedCreateWithoutAiWorkoutsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutAiWorkoutsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutAiWorkoutsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutAiWorkoutsInput, Prisma.UserUncheckedCreateWithoutAiWorkoutsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutAiWorkoutsInput
  upsert?: Prisma.UserUpsertWithoutAiWorkoutsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutAiWorkoutsInput, Prisma.UserUpdateWithoutAiWorkoutsInput>, Prisma.UserUncheckedUpdateWithoutAiWorkoutsInput>
}

export type UserCreateWithoutFeatureSelectionsInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  journalEntries?: Prisma.JournalEntryCreateNestedManyWithoutUserInput
  workoutLogs?: Prisma.WorkoutLogCreateNestedManyWithoutUserInput
  calendarItems?: Prisma.CalendarItemCreateNestedManyWithoutUserInput
  sleepLogs?: Prisma.SleepLogCreateNestedManyWithoutUserInput
  analyzerFindings?: Prisma.AnalyzerFindingCreateNestedManyWithoutUserInput
  aiWorkouts?: Prisma.AiWorkoutPlanCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutFeatureSelectionsInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  journalEntries?: Prisma.JournalEntryUncheckedCreateNestedManyWithoutUserInput
  workoutLogs?: Prisma.WorkoutLogUncheckedCreateNestedManyWithoutUserInput
  calendarItems?: Prisma.CalendarItemUncheckedCreateNestedManyWithoutUserInput
  sleepLogs?: Prisma.SleepLogUncheckedCreateNestedManyWithoutUserInput
  analyzerFindings?: Prisma.AnalyzerFindingUncheckedCreateNestedManyWithoutUserInput
  aiWorkouts?: Prisma.AiWorkoutPlanUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutFeatureSelectionsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutFeatureSelectionsInput, Prisma.UserUncheckedCreateWithoutFeatureSelectionsInput>
}

export type UserUpsertWithoutFeatureSelectionsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutFeatureSelectionsInput, Prisma.UserUncheckedUpdateWithoutFeatureSelectionsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutFeatureSelectionsInput, Prisma.UserUncheckedCreateWithoutFeatureSelectionsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutFeatureSelectionsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutFeatureSelectionsInput, Prisma.UserUncheckedUpdateWithoutFeatureSelectionsInput>
}

export type UserUpdateWithoutFeatureSelectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  journalEntries?: Prisma.JournalEntryUpdateManyWithoutUserNestedInput
  workoutLogs?: Prisma.WorkoutLogUpdateManyWithoutUserNestedInput
  calendarItems?: Prisma.CalendarItemUpdateManyWithoutUserNestedInput
  sleepLogs?: Prisma.SleepLogUpdateManyWithoutUserNestedInput
  analyzerFindings?: Prisma.AnalyzerFindingUpdateManyWithoutUserNestedInput
  aiWorkouts?: Prisma.AiWorkoutPlanUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutFeatureSelectionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  journalEntries?: Prisma.JournalEntryUncheckedUpdateManyWithoutUserNestedInput
  workoutLogs?: Prisma.WorkoutLogUncheckedUpdateManyWithoutUserNestedInput
  calendarItems?: Prisma.CalendarItemUncheckedUpdateManyWithoutUserNestedInput
  sleepLogs?: Prisma.SleepLogUncheckedUpdateManyWithoutUserNestedInput
  analyzerFindings?: Prisma.AnalyzerFindingUncheckedUpdateManyWithoutUserNestedInput
  aiWorkouts?: Prisma.AiWorkoutPlanUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutJournalEntriesInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  featureSelections?: Prisma.FeatureSelectionsCreateNestedManyWithoutUserInput
  workoutLogs?: Prisma.WorkoutLogCreateNestedManyWithoutUserInput
  calendarItems?: Prisma.CalendarItemCreateNestedManyWithoutUserInput
  sleepLogs?: Prisma.SleepLogCreateNestedManyWithoutUserInput
  analyzerFindings?: Prisma.AnalyzerFindingCreateNestedManyWithoutUserInput
  aiWorkouts?: Prisma.AiWorkoutPlanCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutJournalEntriesInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  featureSelections?: Prisma.FeatureSelectionsUncheckedCreateNestedManyWithoutUserInput
  workoutLogs?: Prisma.WorkoutLogUncheckedCreateNestedManyWithoutUserInput
  calendarItems?: Prisma.CalendarItemUncheckedCreateNestedManyWithoutUserInput
  sleepLogs?: Prisma.SleepLogUncheckedCreateNestedManyWithoutUserInput
  analyzerFindings?: Prisma.AnalyzerFindingUncheckedCreateNestedManyWithoutUserInput
  aiWorkouts?: Prisma.AiWorkoutPlanUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutJournalEntriesInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutJournalEntriesInput, Prisma.UserUncheckedCreateWithoutJournalEntriesInput>
}

export type UserUpsertWithoutJournalEntriesInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutJournalEntriesInput, Prisma.UserUncheckedUpdateWithoutJournalEntriesInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutJournalEntriesInput, Prisma.UserUncheckedCreateWithoutJournalEntriesInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutJournalEntriesInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutJournalEntriesInput, Prisma.UserUncheckedUpdateWithoutJournalEntriesInput>
}

export type UserUpdateWithoutJournalEntriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  featureSelections?: Prisma.FeatureSelectionsUpdateManyWithoutUserNestedInput
  workoutLogs?: Prisma.WorkoutLogUpdateManyWithoutUserNestedInput
  calendarItems?: Prisma.CalendarItemUpdateManyWithoutUserNestedInput
  sleepLogs?: Prisma.SleepLogUpdateManyWithoutUserNestedInput
  analyzerFindings?: Prisma.AnalyzerFindingUpdateManyWithoutUserNestedInput
  aiWorkouts?: Prisma.AiWorkoutPlanUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutJournalEntriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  featureSelections?: Prisma.FeatureSelectionsUncheckedUpdateManyWithoutUserNestedInput
  workoutLogs?: Prisma.WorkoutLogUncheckedUpdateManyWithoutUserNestedInput
  calendarItems?: Prisma.CalendarItemUncheckedUpdateManyWithoutUserNestedInput
  sleepLogs?: Prisma.SleepLogUncheckedUpdateManyWithoutUserNestedInput
  analyzerFindings?: Prisma.AnalyzerFindingUncheckedUpdateManyWithoutUserNestedInput
  aiWorkouts?: Prisma.AiWorkoutPlanUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutWorkoutLogsInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  featureSelections?: Prisma.FeatureSelectionsCreateNestedManyWithoutUserInput
  journalEntries?: Prisma.JournalEntryCreateNestedManyWithoutUserInput
  calendarItems?: Prisma.CalendarItemCreateNestedManyWithoutUserInput
  sleepLogs?: Prisma.SleepLogCreateNestedManyWithoutUserInput
  analyzerFindings?: Prisma.AnalyzerFindingCreateNestedManyWithoutUserInput
  aiWorkouts?: Prisma.AiWorkoutPlanCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutWorkoutLogsInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  featureSelections?: Prisma.FeatureSelectionsUncheckedCreateNestedManyWithoutUserInput
  journalEntries?: Prisma.JournalEntryUncheckedCreateNestedManyWithoutUserInput
  calendarItems?: Prisma.CalendarItemUncheckedCreateNestedManyWithoutUserInput
  sleepLogs?: Prisma.SleepLogUncheckedCreateNestedManyWithoutUserInput
  analyzerFindings?: Prisma.AnalyzerFindingUncheckedCreateNestedManyWithoutUserInput
  aiWorkouts?: Prisma.AiWorkoutPlanUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutWorkoutLogsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutWorkoutLogsInput, Prisma.UserUncheckedCreateWithoutWorkoutLogsInput>
}

export type UserUpsertWithoutWorkoutLogsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutWorkoutLogsInput, Prisma.UserUncheckedUpdateWithoutWorkoutLogsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutWorkoutLogsInput, Prisma.UserUncheckedCreateWithoutWorkoutLogsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutWorkoutLogsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutWorkoutLogsInput, Prisma.UserUncheckedUpdateWithoutWorkoutLogsInput>
}

export type UserUpdateWithoutWorkoutLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  featureSelections?: Prisma.FeatureSelectionsUpdateManyWithoutUserNestedInput
  journalEntries?: Prisma.JournalEntryUpdateManyWithoutUserNestedInput
  calendarItems?: Prisma.CalendarItemUpdateManyWithoutUserNestedInput
  sleepLogs?: Prisma.SleepLogUpdateManyWithoutUserNestedInput
  analyzerFindings?: Prisma.AnalyzerFindingUpdateManyWithoutUserNestedInput
  aiWorkouts?: Prisma.AiWorkoutPlanUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutWorkoutLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  featureSelections?: Prisma.FeatureSelectionsUncheckedUpdateManyWithoutUserNestedInput
  journalEntries?: Prisma.JournalEntryUncheckedUpdateManyWithoutUserNestedInput
  calendarItems?: Prisma.CalendarItemUncheckedUpdateManyWithoutUserNestedInput
  sleepLogs?: Prisma.SleepLogUncheckedUpdateManyWithoutUserNestedInput
  analyzerFindings?: Prisma.AnalyzerFindingUncheckedUpdateManyWithoutUserNestedInput
  aiWorkouts?: Prisma.AiWorkoutPlanUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutCalendarItemsInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  featureSelections?: Prisma.FeatureSelectionsCreateNestedManyWithoutUserInput
  journalEntries?: Prisma.JournalEntryCreateNestedManyWithoutUserInput
  workoutLogs?: Prisma.WorkoutLogCreateNestedManyWithoutUserInput
  sleepLogs?: Prisma.SleepLogCreateNestedManyWithoutUserInput
  analyzerFindings?: Prisma.AnalyzerFindingCreateNestedManyWithoutUserInput
  aiWorkouts?: Prisma.AiWorkoutPlanCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutCalendarItemsInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  featureSelections?: Prisma.FeatureSelectionsUncheckedCreateNestedManyWithoutUserInput
  journalEntries?: Prisma.JournalEntryUncheckedCreateNestedManyWithoutUserInput
  workoutLogs?: Prisma.WorkoutLogUncheckedCreateNestedManyWithoutUserInput
  sleepLogs?: Prisma.SleepLogUncheckedCreateNestedManyWithoutUserInput
  analyzerFindings?: Prisma.AnalyzerFindingUncheckedCreateNestedManyWithoutUserInput
  aiWorkouts?: Prisma.AiWorkoutPlanUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutCalendarItemsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutCalendarItemsInput, Prisma.UserUncheckedCreateWithoutCalendarItemsInput>
}

export type UserUpsertWithoutCalendarItemsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutCalendarItemsInput, Prisma.UserUncheckedUpdateWithoutCalendarItemsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutCalendarItemsInput, Prisma.UserUncheckedCreateWithoutCalendarItemsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutCalendarItemsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutCalendarItemsInput, Prisma.UserUncheckedUpdateWithoutCalendarItemsInput>
}

export type UserUpdateWithoutCalendarItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  featureSelections?: Prisma.FeatureSelectionsUpdateManyWithoutUserNestedInput
  journalEntries?: Prisma.JournalEntryUpdateManyWithoutUserNestedInput
  workoutLogs?: Prisma.WorkoutLogUpdateManyWithoutUserNestedInput
  sleepLogs?: Prisma.SleepLogUpdateManyWithoutUserNestedInput
  analyzerFindings?: Prisma.AnalyzerFindingUpdateManyWithoutUserNestedInput
  aiWorkouts?: Prisma.AiWorkoutPlanUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutCalendarItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  featureSelections?: Prisma.FeatureSelectionsUncheckedUpdateManyWithoutUserNestedInput
  journalEntries?: Prisma.JournalEntryUncheckedUpdateManyWithoutUserNestedInput
  workoutLogs?: Prisma.WorkoutLogUncheckedUpdateManyWithoutUserNestedInput
  sleepLogs?: Prisma.SleepLogUncheckedUpdateManyWithoutUserNestedInput
  analyzerFindings?: Prisma.AnalyzerFindingUncheckedUpdateManyWithoutUserNestedInput
  aiWorkouts?: Prisma.AiWorkoutPlanUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutSleepLogsInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  featureSelections?: Prisma.FeatureSelectionsCreateNestedManyWithoutUserInput
  journalEntries?: Prisma.JournalEntryCreateNestedManyWithoutUserInput
  workoutLogs?: Prisma.WorkoutLogCreateNestedManyWithoutUserInput
  calendarItems?: Prisma.CalendarItemCreateNestedManyWithoutUserInput
  analyzerFindings?: Prisma.AnalyzerFindingCreateNestedManyWithoutUserInput
  aiWorkouts?: Prisma.AiWorkoutPlanCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutSleepLogsInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  featureSelections?: Prisma.FeatureSelectionsUncheckedCreateNestedManyWithoutUserInput
  journalEntries?: Prisma.JournalEntryUncheckedCreateNestedManyWithoutUserInput
  workoutLogs?: Prisma.WorkoutLogUncheckedCreateNestedManyWithoutUserInput
  calendarItems?: Prisma.CalendarItemUncheckedCreateNestedManyWithoutUserInput
  analyzerFindings?: Prisma.AnalyzerFindingUncheckedCreateNestedManyWithoutUserInput
  aiWorkouts?: Prisma.AiWorkoutPlanUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutSleepLogsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutSleepLogsInput, Prisma.UserUncheckedCreateWithoutSleepLogsInput>
}

export type UserUpsertWithoutSleepLogsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutSleepLogsInput, Prisma.UserUncheckedUpdateWithoutSleepLogsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutSleepLogsInput, Prisma.UserUncheckedCreateWithoutSleepLogsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutSleepLogsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutSleepLogsInput, Prisma.UserUncheckedUpdateWithoutSleepLogsInput>
}

export type UserUpdateWithoutSleepLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  featureSelections?: Prisma.FeatureSelectionsUpdateManyWithoutUserNestedInput
  journalEntries?: Prisma.JournalEntryUpdateManyWithoutUserNestedInput
  workoutLogs?: Prisma.WorkoutLogUpdateManyWithoutUserNestedInput
  calendarItems?: Prisma.CalendarItemUpdateManyWithoutUserNestedInput
  analyzerFindings?: Prisma.AnalyzerFindingUpdateManyWithoutUserNestedInput
  aiWorkouts?: Prisma.AiWorkoutPlanUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutSleepLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  featureSelections?: Prisma.FeatureSelectionsUncheckedUpdateManyWithoutUserNestedInput
  journalEntries?: Prisma.JournalEntryUncheckedUpdateManyWithoutUserNestedInput
  workoutLogs?: Prisma.WorkoutLogUncheckedUpdateManyWithoutUserNestedInput
  calendarItems?: Prisma.CalendarItemUncheckedUpdateManyWithoutUserNestedInput
  analyzerFindings?: Prisma.AnalyzerFindingUncheckedUpdateManyWithoutUserNestedInput
  aiWorkouts?: Prisma.AiWorkoutPlanUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutAnalyzerFindingsInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  featureSelections?: Prisma.FeatureSelectionsCreateNestedManyWithoutUserInput
  journalEntries?: Prisma.JournalEntryCreateNestedManyWithoutUserInput
  workoutLogs?: Prisma.WorkoutLogCreateNestedManyWithoutUserInput
  calendarItems?: Prisma.CalendarItemCreateNestedManyWithoutUserInput
  sleepLogs?: Prisma.SleepLogCreateNestedManyWithoutUserInput
  aiWorkouts?: Prisma.AiWorkoutPlanCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutAnalyzerFindingsInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  featureSelections?: Prisma.FeatureSelectionsUncheckedCreateNestedManyWithoutUserInput
  journalEntries?: Prisma.JournalEntryUncheckedCreateNestedManyWithoutUserInput
  workoutLogs?: Prisma.WorkoutLogUncheckedCreateNestedManyWithoutUserInput
  calendarItems?: Prisma.CalendarItemUncheckedCreateNestedManyWithoutUserInput
  sleepLogs?: Prisma.SleepLogUncheckedCreateNestedManyWithoutUserInput
  aiWorkouts?: Prisma.AiWorkoutPlanUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutAnalyzerFindingsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutAnalyzerFindingsInput, Prisma.UserUncheckedCreateWithoutAnalyzerFindingsInput>
}

export type UserUpsertWithoutAnalyzerFindingsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutAnalyzerFindingsInput, Prisma.UserUncheckedUpdateWithoutAnalyzerFindingsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutAnalyzerFindingsInput, Prisma.UserUncheckedCreateWithoutAnalyzerFindingsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutAnalyzerFindingsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutAnalyzerFindingsInput, Prisma.UserUncheckedUpdateWithoutAnalyzerFindingsInput>
}

export type UserUpdateWithoutAnalyzerFindingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  featureSelections?: Prisma.FeatureSelectionsUpdateManyWithoutUserNestedInput
  journalEntries?: Prisma.JournalEntryUpdateManyWithoutUserNestedInput
  workoutLogs?: Prisma.WorkoutLogUpdateManyWithoutUserNestedInput
  calendarItems?: Prisma.CalendarItemUpdateManyWithoutUserNestedInput
  sleepLogs?: Prisma.SleepLogUpdateManyWithoutUserNestedInput
  aiWorkouts?: Prisma.AiWorkoutPlanUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutAnalyzerFindingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  featureSelections?: Prisma.FeatureSelectionsUncheckedUpdateManyWithoutUserNestedInput
  journalEntries?: Prisma.JournalEntryUncheckedUpdateManyWithoutUserNestedInput
  workoutLogs?: Prisma.WorkoutLogUncheckedUpdateManyWithoutUserNestedInput
  calendarItems?: Prisma.CalendarItemUncheckedUpdateManyWithoutUserNestedInput
  sleepLogs?: Prisma.SleepLogUncheckedUpdateManyWithoutUserNestedInput
  aiWorkouts?: Prisma.AiWorkoutPlanUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutAiWorkoutsInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  featureSelections?: Prisma.FeatureSelectionsCreateNestedManyWithoutUserInput
  journalEntries?: Prisma.JournalEntryCreateNestedManyWithoutUserInput
  workoutLogs?: Prisma.WorkoutLogCreateNestedManyWithoutUserInput
  calendarItems?: Prisma.CalendarItemCreateNestedManyWithoutUserInput
  sleepLogs?: Prisma.SleepLogCreateNestedManyWithoutUserInput
  analyzerFindings?: Prisma.AnalyzerFindingCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutAiWorkoutsInput = {
  id?: string
  email?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  featureSelections?: Prisma.FeatureSelectionsUncheckedCreateNestedManyWithoutUserInput
  journalEntries?: Prisma.JournalEntryUncheckedCreateNestedManyWithoutUserInput
  workoutLogs?: Prisma.WorkoutLogUncheckedCreateNestedManyWithoutUserInput
  calendarItems?: Prisma.CalendarItemUncheckedCreateNestedManyWithoutUserInput
  sleepLogs?: Prisma.SleepLogUncheckedCreateNestedManyWithoutUserInput
  analyzerFindings?: Prisma.AnalyzerFindingUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutAiWorkoutsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutAiWorkoutsInput, Prisma.UserUncheckedCreateWithoutAiWorkoutsInput>
}

export type UserUpsertWithoutAiWorkoutsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutAiWorkoutsInput, Prisma.UserUncheckedUpdateWithoutAiWorkoutsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutAiWorkoutsInput, Prisma.UserUncheckedCreateWithoutAiWorkoutsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutAiWorkoutsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutAiWorkoutsInput, Prisma.UserUncheckedUpdateWithoutAiWorkoutsInput>
}

export type UserUpdateWithoutAiWorkoutsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  featureSelections?: Prisma.FeatureSelectionsUpdateManyWithoutUserNestedInput
  journalEntries?: Prisma.JournalEntryUpdateManyWithoutUserNestedInput
  workoutLogs?: Prisma.WorkoutLogUpdateManyWithoutUserNestedInput
  calendarItems?: Prisma.CalendarItemUpdateManyWithoutUserNestedInput
  sleepLogs?: Prisma.SleepLogUpdateManyWithoutUserNestedInput
  analyzerFindings?: Prisma.AnalyzerFindingUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutAiWorkoutsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  featureSelections?: Prisma.FeatureSelectionsUncheckedUpdateManyWithoutUserNestedInput
  journalEntries?: Prisma.JournalEntryUncheckedUpdateManyWithoutUserNestedInput
  workoutLogs?: Prisma.WorkoutLogUncheckedUpdateManyWithoutUserNestedInput
  calendarItems?: Prisma.CalendarItemUncheckedUpdateManyWithoutUserNestedInput
  sleepLogs?: Prisma.SleepLogUncheckedUpdateManyWithoutUserNestedInput
  analyzerFindings?: Prisma.AnalyzerFindingUncheckedUpdateManyWithoutUserNestedInput
}


/**
 * Count Type UserCountOutputType
 */

export type UserCountOutputType = {
  featureSelections: number
  journalEntries: number
  workoutLogs: number
  calendarItems: number
  sleepLogs: number
  analyzerFindings: number
  aiWorkouts: number
}

export type UserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  featureSelections?: boolean | UserCountOutputTypeCountFeatureSelectionsArgs
  journalEntries?: boolean | UserCountOutputTypeCountJournalEntriesArgs
  workoutLogs?: boolean | UserCountOutputTypeCountWorkoutLogsArgs
  calendarItems?: boolean | UserCountOutputTypeCountCalendarItemsArgs
  sleepLogs?: boolean | UserCountOutputTypeCountSleepLogsArgs
  analyzerFindings?: boolean | UserCountOutputTypeCountAnalyzerFindingsArgs
  aiWorkouts?: boolean | UserCountOutputTypeCountAiWorkoutsArgs
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCountOutputType
   */
  select?: Prisma.UserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountFeatureSelectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FeatureSelectionsWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountJournalEntriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.JournalEntryWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountWorkoutLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkoutLogWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountCalendarItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CalendarItemWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountSleepLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SleepLogWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountAnalyzerFindingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AnalyzerFindingWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountAiWorkoutsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AiWorkoutPlanWhereInput
}


export type UserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  featureSelections?: boolean | Prisma.User$featureSelectionsArgs<ExtArgs>
  journalEntries?: boolean | Prisma.User$journalEntriesArgs<ExtArgs>
  workoutLogs?: boolean | Prisma.User$workoutLogsArgs<ExtArgs>
  calendarItems?: boolean | Prisma.User$calendarItemsArgs<ExtArgs>
  sleepLogs?: boolean | Prisma.User$sleepLogsArgs<ExtArgs>
  analyzerFindings?: boolean | Prisma.User$analyzerFindingsArgs<ExtArgs>
  aiWorkouts?: boolean | Prisma.User$aiWorkoutsArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  email?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectScalar = {
  id?: boolean
  email?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type UserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "email" | "createdAt" | "updatedAt", ExtArgs["result"]["user"]>
export type UserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  featureSelections?: boolean | Prisma.User$featureSelectionsArgs<ExtArgs>
  journalEntries?: boolean | Prisma.User$journalEntriesArgs<ExtArgs>
  workoutLogs?: boolean | Prisma.User$workoutLogsArgs<ExtArgs>
  calendarItems?: boolean | Prisma.User$calendarItemsArgs<ExtArgs>
  sleepLogs?: boolean | Prisma.User$sleepLogsArgs<ExtArgs>
  analyzerFindings?: boolean | Prisma.User$analyzerFindingsArgs<ExtArgs>
  aiWorkouts?: boolean | Prisma.User$aiWorkoutsArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}
export type UserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type UserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $UserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "User"
  objects: {
    featureSelections: Prisma.$FeatureSelectionsPayload<ExtArgs>[]
    journalEntries: Prisma.$JournalEntryPayload<ExtArgs>[]
    workoutLogs: Prisma.$WorkoutLogPayload<ExtArgs>[]
    calendarItems: Prisma.$CalendarItemPayload<ExtArgs>[]
    sleepLogs: Prisma.$SleepLogPayload<ExtArgs>[]
    analyzerFindings: Prisma.$AnalyzerFindingPayload<ExtArgs>[]
    aiWorkouts: Prisma.$AiWorkoutPlanPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    email: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["user"]>
  composites: {}
}

export type UserGetPayload<S extends boolean | null | undefined | UserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPayload, S>

export type UserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCountAggregateInputType | true
  }

export interface UserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['User'], meta: { name: 'User' } }
  /**
   * Find zero or one User that matches the filter.
   * @param {UserFindUniqueArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFindUniqueOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.user.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userWithIdOnly = await prisma.user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFindManyArgs>(args?: Prisma.SelectSubset<T, UserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User.
   * @param {UserCreateArgs} args - Arguments to create a User.
   * @example
   * // Create one User
   * const User = await prisma.user.create({
   *   data: {
   *     // ... data to create a User
   *   }
   * })
   * 
   */
  create<T extends UserCreateArgs>(args: Prisma.SelectSubset<T, UserCreateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UserCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {UserCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const userWithIdOnly = await prisma.user.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User.
   * @param {UserDeleteArgs} args - Arguments to delete one User.
   * @example
   * // Delete one User
   * const User = await prisma.user.delete({
   *   where: {
   *     // ... filter to delete one User
   *   }
   * })
   * 
   */
  delete<T extends UserDeleteArgs>(args: Prisma.SelectSubset<T, UserDeleteArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User.
   * @param {UserUpdateArgs} args - Arguments to update one User.
   * @example
   * // Update one User
   * const user = await prisma.user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserUpdateArgs>(args: Prisma.SelectSubset<T, UserUpdateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UserDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserUpdateManyArgs>(args: Prisma.SelectSubset<T, UserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {UserUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const userWithIdOnly = await prisma.user.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User.
   * @param {UserUpsertArgs} args - Arguments to update or create a User.
   * @example
   * // Update or create a User
   * const user = await prisma.user.upsert({
   *   create: {
   *     // ... data to create a User
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User we want to update
   *   }
   * })
   */
  upsert<T extends UserUpsertArgs>(args: Prisma.SelectSubset<T, UserUpsertArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.user.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UserCountArgs>(
    args?: Prisma.Subset<T, UserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserAggregateArgs>(args: Prisma.Subset<T, UserAggregateArgs>): Prisma.PrismaPromise<GetUserAggregateType<T>>

  /**
   * Group by User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserGroupByArgs['orderBy'] }
      : { orderBy?: UserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the User model
 */
readonly fields: UserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for User.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  featureSelections<T extends Prisma.User$featureSelectionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$featureSelectionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeatureSelectionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  journalEntries<T extends Prisma.User$journalEntriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$journalEntriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JournalEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  workoutLogs<T extends Prisma.User$workoutLogsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$workoutLogsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkoutLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  calendarItems<T extends Prisma.User$calendarItemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$calendarItemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CalendarItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  sleepLogs<T extends Prisma.User$sleepLogsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$sleepLogsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SleepLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  analyzerFindings<T extends Prisma.User$analyzerFindingsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$analyzerFindingsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnalyzerFindingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  aiWorkouts<T extends Prisma.User$aiWorkoutsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$aiWorkoutsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AiWorkoutPlanPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the User model
 */
export interface UserFieldRefs {
  readonly id: Prisma.FieldRef<"User", 'String'>
  readonly email: Prisma.FieldRef<"User", 'String'>
  readonly createdAt: Prisma.FieldRef<"User", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"User", 'DateTime'>
}
    

// Custom InputTypes
/**
 * User findUnique
 */
export type UserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findUniqueOrThrow
 */
export type UserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findFirst
 */
export type UserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findFirstOrThrow
 */
export type UserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findMany
 */
export type UserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User create
 */
export type UserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to create a User.
   */
  data: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
}

/**
 * User createMany
 */
export type UserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
}

/**
 * User createManyAndReturn
 */
export type UserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
}

/**
 * User update
 */
export type UserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to update a User.
   */
  data: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
  /**
   * Choose, which User to update.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User updateMany
 */
export type UserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User updateManyAndReturn
 */
export type UserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User upsert
 */
export type UserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The filter to search for the User to update in case it exists.
   */
  where: Prisma.UserWhereUniqueInput
  /**
   * In case the User found by the `where` argument doesn't exist, create a new User with this data.
   */
  create: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
  /**
   * In case the User was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
}

/**
 * User delete
 */
export type UserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter which User to delete.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User deleteMany
 */
export type UserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * User.featureSelections
 */
export type User$featureSelectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FeatureSelections
   */
  select?: Prisma.FeatureSelectionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FeatureSelections
   */
  omit?: Prisma.FeatureSelectionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeatureSelectionsInclude<ExtArgs> | null
  where?: Prisma.FeatureSelectionsWhereInput
  orderBy?: Prisma.FeatureSelectionsOrderByWithRelationInput | Prisma.FeatureSelectionsOrderByWithRelationInput[]
  cursor?: Prisma.FeatureSelectionsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FeatureSelectionsScalarFieldEnum | Prisma.FeatureSelectionsScalarFieldEnum[]
}

/**
 * User.journalEntries
 */
export type User$journalEntriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JournalEntry
   */
  select?: Prisma.JournalEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the JournalEntry
   */
  omit?: Prisma.JournalEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JournalEntryInclude<ExtArgs> | null
  where?: Prisma.JournalEntryWhereInput
  orderBy?: Prisma.JournalEntryOrderByWithRelationInput | Prisma.JournalEntryOrderByWithRelationInput[]
  cursor?: Prisma.JournalEntryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.JournalEntryScalarFieldEnum | Prisma.JournalEntryScalarFieldEnum[]
}

/**
 * User.workoutLogs
 */
export type User$workoutLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkoutLog
   */
  select?: Prisma.WorkoutLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkoutLog
   */
  omit?: Prisma.WorkoutLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkoutLogInclude<ExtArgs> | null
  where?: Prisma.WorkoutLogWhereInput
  orderBy?: Prisma.WorkoutLogOrderByWithRelationInput | Prisma.WorkoutLogOrderByWithRelationInput[]
  cursor?: Prisma.WorkoutLogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.WorkoutLogScalarFieldEnum | Prisma.WorkoutLogScalarFieldEnum[]
}

/**
 * User.calendarItems
 */
export type User$calendarItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarItem
   */
  select?: Prisma.CalendarItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarItem
   */
  omit?: Prisma.CalendarItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalendarItemInclude<ExtArgs> | null
  where?: Prisma.CalendarItemWhereInput
  orderBy?: Prisma.CalendarItemOrderByWithRelationInput | Prisma.CalendarItemOrderByWithRelationInput[]
  cursor?: Prisma.CalendarItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CalendarItemScalarFieldEnum | Prisma.CalendarItemScalarFieldEnum[]
}

/**
 * User.sleepLogs
 */
export type User$sleepLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SleepLog
   */
  select?: Prisma.SleepLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SleepLog
   */
  omit?: Prisma.SleepLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SleepLogInclude<ExtArgs> | null
  where?: Prisma.SleepLogWhereInput
  orderBy?: Prisma.SleepLogOrderByWithRelationInput | Prisma.SleepLogOrderByWithRelationInput[]
  cursor?: Prisma.SleepLogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SleepLogScalarFieldEnum | Prisma.SleepLogScalarFieldEnum[]
}

/**
 * User.analyzerFindings
 */
export type User$analyzerFindingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AnalyzerFinding
   */
  select?: Prisma.AnalyzerFindingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AnalyzerFinding
   */
  omit?: Prisma.AnalyzerFindingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnalyzerFindingInclude<ExtArgs> | null
  where?: Prisma.AnalyzerFindingWhereInput
  orderBy?: Prisma.AnalyzerFindingOrderByWithRelationInput | Prisma.AnalyzerFindingOrderByWithRelationInput[]
  cursor?: Prisma.AnalyzerFindingWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AnalyzerFindingScalarFieldEnum | Prisma.AnalyzerFindingScalarFieldEnum[]
}

/**
 * User.aiWorkouts
 */
export type User$aiWorkoutsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiWorkoutPlan
   */
  select?: Prisma.AiWorkoutPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiWorkoutPlan
   */
  omit?: Prisma.AiWorkoutPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiWorkoutPlanInclude<ExtArgs> | null
  where?: Prisma.AiWorkoutPlanWhereInput
  orderBy?: Prisma.AiWorkoutPlanOrderByWithRelationInput | Prisma.AiWorkoutPlanOrderByWithRelationInput[]
  cursor?: Prisma.AiWorkoutPlanWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AiWorkoutPlanScalarFieldEnum | Prisma.AiWorkoutPlanScalarFieldEnum[]
}

/**
 * User without action
 */
export type UserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
}
